### ISSUE TITLE
Proposal to add border color option to Password Input widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4168] opened 2022-10-01 05:06 UTC
## Proposed feature
Option to change and update the border color of the password input widget with the `Border color` property in the style tab.

### Description
Currently, the password input widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="528" alt="Screenshot 2022-10-01 at 10 34 16 AM" src="https://user-images.githubusercontent.com/67645175/193393521-fac92d7b-a5d5-40ee-9e36-45d3ddbe7e41.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by anuj98** [comment] 2022-10-01 05:11
@arpitnath I would like to work on this.

**Comment by arpitnath** [comment] 2022-10-01 05:13
@anuj98, assigning the issue to you 😁

**Comment by Abdirizaks12** [comment] 2022-10-01 05:20
can i also work on it?

**Comment by withshubh** [comment] 2022-10-01 05:31
Hey @Abdirizaks12 👋 
This issue is already assigned.
You are free to explore other issues listed as [hactoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+label%3Ahacktoberfest+sort%3Aupdated-desc) and will be adding more soon.

**Comment by Abdirizaks12** [comment] 2022-10-01 05:33
> Hey @Abdirizaks12 👋 This issue is already assigned. You are free to explore other issues listed as [hactoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+label%3Ahacktoberfest+sort%3Aupdated-desc) and will be adding more soon.

okay,thanks

**Comment by anuj98** [comment] 2022-10-01 06:33
Hey @arpitnath / @withshubh I am getting following error:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/30874550/193396152-748c245b-f312-48fc-998a-586cdf7f951b.png">
Not able to start the server what might be the problem

**Comment by arpitnath** [comment] 2022-10-01 10:09
@anuj98 Can you share the logs?
You can follow the setup guide for docker from [here](https://docs.tooljet.com/docs/contributing-guide/setup/docker)

**Comment by arpitnath** [comment] 2022-10-01 10:27
@anuj98 
For the time being,

**Comment by anuj98** [comment] 2022-10-01 16:26
> #!/bin/bash

These are the logs:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/30874550/193418895-ed884d8f-8a9a-430e-af77-2f1bc18c4f0b.png">

Also I updated the entrypoint.sh as mentioned it didn't work

**Comment by arpitnath** [comment] 2022-10-04 21:29
Hi @anuj98, there is a thread, faced by others in our slack community which can be helpful for you.
I would recommend you to join our [Slack community](https://tooljet.com/slack) 😅

**Comment by anuj98** [comment] 2022-10-15 05:36
Hi @arpitnath I was not able to run the solution. You can assign this to someone else.

**Comment by withshubh** [comment] 2022-10-16 06:43
> Hi @arpitnath I was not able to run the solution. You can assign this to someone else.

Hey @anuj98 - The issue has been unassinged.

**Comment by akarsh-jain-790** [comment] 2022-10-16 06:53
@withshubh can you assign this issue to me?

**Comment by withshubh** [comment] 2022-10-16 12:51
> @withshubh can you assign this issue to me?

Hey @akarsh-jain-790 
An issue was assigned to you earlier and then later you unassigned yourself from that issue. I have already assigned another issue to you. Let's not spam all the issues that are being created. Please comment on only the issue that you believe you'll be able to do. Also, please do inform us if you're not interested in working on an issue before unassigning yourself.

**Comment by AyushK-101** [comment] 2022-10-21 06:13
@withshubh can I work on this?

**Comment by akarsh-jain-790** [comment] 2022-10-22 05:26
I'm working on it

**Comment by withshubh** [comment] 2022-10-23 12:37
> > @withshubh can you assign this issue to me?
> 
> Hey @akarsh-jain-790 An issue was assigned to you earlier and then later you unassigned yourself from that issue. I have already assigned another issue to you. Let's not spam all the issues that are being created. Please comment on only the issue that you believe you'll be able to do. Also, please do inform us if you're not interested in working on an issue before unassigning yourself.

Hey @akarsh-jain-790 
Assigned the issue to you.
And please consider this as our last warning - You can't simply create PRs for the issues that are not assigned to you. We will be forced to close any PR that is created without an issue assigned to you. Please follow the [contributing guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md).

**Comment by akarsh-jain-790** [comment] 2022-10-23 14:30
> > @withshubh can you assign this issue to me?
> 
> Hey @akarsh-jain-790 An issue was assigned to you earlier and then later you unassigned yourself from that issue. I have already assigned another issue to you. Let's not spam all the issues that are being created. Please comment on only the issue that you believe you'll be able to do. Also, please do inform us if you're not interested in working on an issue before unassigning yourself.

@withshubh FYI  I am not spamming on all the issue which are raised. I have only commented to these 4 issues(4448, 4454, 4452, 4450) Also I didn't find any guideline that says you can't ask for more than 1 issues. 

I have asked to assign only those issue which I believe I will able to do (Already made PR for the issues that I got assigned and some of them already got merged)

`please do inform us if you're not interested in working on an issue before unassigning yourself.`

Actually I wasn't knowing that as I didn't find anything in [contributing guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) which says I should inform before unassigning an issue, So I will keep this in mind for future contributions.



> > > @withshubh can you assign this issue to me?
> > 
> > 
> > Hey @akarsh-jain-790 An issue was assigned to you earlier and then later you unassigned yourself from that issue. I have already assigned another issue to you. Let's not spam all the issues that are being created. Please comment on only the issue that you believe you'll be able to do. Also, please do inform us if you're not interested in working on an issue before unassigning yourself.
> 
> Hey @akarsh-jain-790 Assigned the issue to you. And please consider this as our last warning - You can't simply create PRs for the issues that are not assigned to you. We will be forced to close any PR that is created without an issue assigned to you. Please follow the [contributing guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md).

I'm sorry for that, I will not repeat this again.

**Closed** 2023-02-10 08:51 UTC
Labels: good first issue, feature request, hacktoberfest, up-for-grabs, widget, react

**Comment by ThibautMTL** [comment] 2023-03-31 13:52
hi @withshubh
I think the issue is closed without having been resolved. There is still no border option for password input.
