### ISSUE TITLE
[doc] resize the search icon in search bar

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#5099] opened 2022-12-29 09:36 UTC
### Summary

Currently, the search icon on the search bar of the documentation is a bit large.
Update the search icon size to `13x13`

<img width="300" alt="Screenshot 2022-12-28 at 1 42 26 PM" src="https://user-images.githubusercontent.com/25361949/209780487-6aabd580-0ad8-4b50-9a96-a69ddc5fe362.png">

### Issue Type

Documentation feature/update

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs

### Steps to reproduce the issue

1. Open Docs
2. Check the search bar on top-left

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Aashish-Upadhyay-101** [comment] 2022-12-29 11:56
I have done PR #5101

**Comment by rhinoxD** [comment] 2022-12-30 09:10
!assign

**Comment by Aashish-Upadhyay-101** [comment] 2022-12-30 09:55
i will do it

**Comment by Jittojoyes98** [comment] 2023-01-09 07:01
Is someone working on this issue ? @Aashish-Upadhyay-101 are you working on this?

**Comment by Aviroop-001** [comment] 2023-01-15 06:50
I'd like to fix this issue. Please assign me the same.

**Comment by Joshbwr** [comment] 2023-02-25 21:40
@withshubh Can you assign this to me please?

**Comment by girish6701** [comment] 2023-03-24 15:47
Hi @withshubh!
Is this open for contribution? If it is, I would love to contribute to it.

**Comment by withshubh** [comment] 2023-04-04 11:36
Hey @Aviroop-001 - Are you still interested in picking up this issue?
Or I can assign it to @girish6701?

**Comment by alceil** [comment] 2023-04-06 06:44
Can I work on this issue @shubh22 ?

**Comment by harsh472000** [comment] 2023-04-12 05:53
@withshubh 
is this still open ? if it is, I would like to contribute to it.

**Comment by withshubh** [comment] 2023-04-12 07:03
Hey @harsh472000 - Assigned the issue to you.

**Comment by withshubh** [comment] 2023-04-12 07:04
Hey @alceil - Are you still interested in working on this issue?
Or we can assign this to @harsh472000 .

**Comment by alceil** [comment] 2023-04-12 07:07
Yes I am @withshubh

**Comment by withshubh** [comment] 2023-04-12 07:10
@alceil - Thanks for the confirmation. Assigned the issue to you.

@harsh472000 - Please feel free to comment on any other issues with `good first issue` or `up for grabs` label.

**Comment by alceil** [comment] 2023-05-11 03:44
Im not working on it since I was not able to run the project locally itself you can unassign me @withshubh

**Comment by withshubh** [comment] 2023-05-11 05:35
Hey @alceil 
To run the docs locally, go to the `tooljet/docs` directory and run the following commands
```
yarn install
```
```
yarn start
```
Note: node v16.14 is required

Let me know if you still want me to unassign the issue

**Comment by alceil** [comment] 2023-05-11 09:35
I tried to setup the project locally multiple times but was not able to. Since im a windows user I was asked to follow ubuntu docs and use ws2 to run it locally. But after mutliple tries wasnt able to do it.  I would like to unassign from this issue since i wont be able to contribute to it.

**Comment by withshubh** [comment] 2023-05-11 09:37
Sure! The issue has been unassigned.
Just FYI: contributing to documentation doesn't requires to setup the ToolJet locally.

**Comment by Mohiit70** [comment] 2023-05-12 19:38
To implement this change, I searched for the code in the repository but was unable to find it. It's possible that the code is not publicly available or is located in a private repository. As a result, I was unable to provide a code snippet for this change

**Comment by withshubh** [comment] 2023-05-19 10:07
Hey @Mohiit70 - This only requires a small CSS change. :)

**Comment by Mohiit70** [comment] 2023-06-02 16:27
> hi can i work on this

Before you can begin, you need to assign it to the appropriate person within tooljet organization. Once the issue is assigned, you will be notified, and then you can proceed with your work. Let me know if you have any further questions. Thank you!

**Comment by krimoelbahri** [comment] 2023-06-04 09:46
yeah, i want this issue to be assigned to me. and i am waiting

**Comment by withshubh** [comment] 2023-06-07 06:01
Hey @krimoelbahri There is another issue assigned to you and the PR is under review.
Since the issue holds the good first issue tag which is for welcoming new contributors let's give someone new the opportunity to work on this issue.
I hope you understand.

**Comment by sudip57** [comment] 2023-07-15 03:50
Hey @withshubh I want to contribute to this issue. Please assign it to me

**Comment by JunedKhan101** [comment] 2023-07-16 07:47
@withshubh Can I pick this up?

**Comment by tejakummarikuntla** [comment] 2023-07-24 16:34
Hey @sudip57 , thanks for your interest; Assigend this to you.

**Comment by sudip57** [comment] 2023-07-25 16:17
@tejakummarikuntla I have raised pr

**Comment by ishsarin** [comment] 2023-07-29 19:27
Hi, if this issue is open could I contribute?

**Closed** 2023-08-10 11:27 UTC
Labels: documentation, good first issue, up-for-grabs
