### ISSUE TITLE
Validation for input fields

### ISSUE THREAD

**Issue by Navaneeth-pk** [ToolJet/ToolJet#692] opened 2021-09-05 15:58 UTC
Goal: On the inspector, the option for validating the input values of different fields should be shown.

Validation options: 
a) Regex - test the input value against a regular expression
b) Min length - mark the `isValid` property of field as `false` and show an error if the minimum number of characters is not met.
c) Max length - mark the `isValid` property of field as `false` and show an error if the number of characters is more than the max length. 
d) Custom rule - if the code returns a string, the `isValid` property will be marked as `false` and the string will  be displayed as the error.

UI: Tabler supports fields with validation states ( https://preview.tabler.io/form-elements.html ) 

![image](https://user-images.githubusercontent.com/7828962/132133281-15b5571d-ccd9-43f9-b807-e04f68a5880d.png)

NOTE: The validation feature should also work for editable table cells.

**Comment by TheLearneer** [comment] 2021-10-09 05:19
@Navaneeth-pk Hi there again. This issue also seems to have obtained a PR for fix and is also merged, but the issue is still open.

**Closed** 2021-10-10 08:32 UTC
Labels: feature request
