### ISSUE TITLE
Change text of CTA for first application

### ISSUE THREAD

**Issue by shubh22** [ToolJet/ToolJet#6052] opened 2023-04-17 11:49 UTC
Change text from "New app from scratch" to "Create new application"
![ToolJet-Dashboard (3)](https://user-images.githubusercontent.com/2677855/232475677-6599d98e-65b7-4744-a73d-7b28935fec01.png)

**Comment by snehal741** [comment] 2023-04-17 12:37
Hey @shubh22 can I work on this issue?

**Comment by withshubh** [comment] 2023-04-17 13:15
> Hey @shubh22 can I work on this issue?

Hey @snehal741 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.
Please feel free to join our **[Slack Community](https://tooljet.com/slack)** if you have any questions.

**Comment by k-deepak04** [comment] 2023-04-17 15:37
@shubh22 shall i work on this ?

**Comment by withshubh** [comment] 2023-04-18 05:39
> @shubh22 shall i work on this ?

Hey @k-deepak04 - The issue is already assigned to someone. Please find other open issues with `good-first-isssue` or `up-for-grabs`

**Comment by snehal741** [comment] 2023-04-20 18:16
@shubh22 I have made a pull request #6087 , can you review it?

**Closed** 2023-04-29 14:37 UTC
Labels: enhancement, good first issue, up-for-grabs
