### ISSUE TITLE
[refactor]: Update descriptions(tooltips) for calendar, iframe, code editor and tabs components

### ISSUE THREAD

**Issue by karan-rathod-316** [ToolJet/ToolJet#7522] opened 2023-09-27 15:17 UTC
### Summary
Descriptions(tooltips) for components need to be updated.

### How to reproduce the issue?

1. Open the ToolJet App-Builder
2. Hover over the components in the Components library on the right
3. You can see descriptions(tooltips) for each component on hover

### Screenshots 

Table component description(tooltip) example:

<img width="958" alt="table-en" src="https://github.com/ToolJet/ToolJet/assets/58169101/e80aa917-6ef0-4dd0-a0c6-ea895d494aba">

<img width="840" alt="table-widget-config" src="https://github.com/ToolJet/ToolJet/assets/58169101/ace5382a-b17b-413b-8114-a7fdd2d50629">

![image](https://github.com/ToolJet/ToolJet/assets/58169101/4f28eb6f-585d-424d-9c84-4ac4ece23f84)

### Any possible solutions?

Replace the current labels in the `widgetConfig.js` and `en.json` files according to the below table.

| Name             | Current Description                  | New Description       |
|:-----------------|:---------------------------------|:----------------------|
| Calendar         | Calendar                         | Display calendar events         |
| Iframe           | Display an Iframe                | Embed external content       |
| Code Editor      | Code Editor                      | Edit source code               |
| Tabs             | Tabs component                   | Organize content in tabs        |

### If the bug is confirmed, would you be willing to submit a PR?
No

### Code of Conduct

- [ ] I agree to follow the [ToolJet Code of Conduct](https://docs.tooljet.com/docs/contributing-guide/code-of-conduct)

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by nayangoyal** [comment] 2023-09-27 15:23
Hi, @karan-rathod-316 can you assign this issue to me? I want to work on this issue.

**Comment by karan-rathod-316** [comment] 2023-09-28 09:09
Hi @nayangoyal,

As this issue is tagged as a `good-first-issue` and we've already assigned you on issue, we'll wait for other first-time contributors to pick this up. 

Please feel free to monitor other issues that may pique your interest. Thank you for your time and consideration.

**Comment by ghOst-vedant** [comment] 2023-09-28 10:03
Hi, @karan-rathod-316 sir, I would like to work on this as this will be my first contribution.

**Comment by karan-rathod-316** [comment] 2023-09-28 10:07
Hi @ghOst-vedant,

Thank you so much for your interest in contributing to ToolJet. Assigning the issue to you.

To seek assistance or resolve issues, we invite you to join our active community of ToolJet developers on [Slack](https://tooljet.com/slack).

**Comment by ghOst-vedant** [comment] 2023-09-29 04:01
@karan-rathod-316 followed the steps in the setup but not able to build locally..
Help

**Comment by ghOst-vedant** [comment] 2023-09-30 18:35
@karan-rathod-316 I've created a pr

**Comment by suiisharma** [comment] 2023-10-03 17:34
Hello @karan-rathod-316 ,

I am interested in contributing to this issue.
Can you assign it to me ?

**Comment by ghOst-vedant** [comment] 2023-10-04 02:54
@suiisharma better try another cause my pr ready and it's awaiting maintainer review so better get going good luck🙌🏻

**Comment by Omsoni06** [comment] 2023-10-04 06:21
> @suiisharma better try another cause my pr ready and it's awaiting maintainer review so better get going good luck🙌🏻

PR was already closed for this issue but the issue is still open

**Closed** 2023-10-20 09:14 UTC
Labels: enhancement, good first issue, hacktoberfest, up-for-grabs
