### ISSUE TITLE
[localization] Translate Widget and Widget Manager to French

### ISSUE THREAD

**Issue by arushmangal** [ToolJet/ToolJet#4352] opened 2022-10-08 04:45 UTC
### Is your proposal related to a problem?
Add translations for Widget and Widget Manager strings in French.

### Describe the solution you'd like
The strings for 'Widget' and 'Widget Manager' to be translated to French

![Annotation 2022-10-08 101047](https://user-images.githubusercontent.com/83538403/194688840-ee305f5a-6256-4119-bcd3-a39833ef9999.jpg)

### If the feature is approved, would you be willing to submit a PR?
Yes!

**Comment by Shelly011s** [comment] 2022-10-08 21:08
I would like to take on this issue.

**Comment by withshubh** [comment] 2022-10-13 11:25
Hey @arushmangal 👋 

Thanks for your interest in contributing to ToolJet. 

Closing the issue as we are only accepting localization contributions for the issues that we create unless the issue is created by the native speaker. You can always check out other open issues. 😇

**Closed by withshubh** 2022-10-13 11:25 UTC
Labels: feature request
