### ISSUE TITLE
Lint and Prettier Errors Present in Code Base

### ISSUE THREAD

**Issue by Nathan-Bisson** [ToolJet/ToolJet#3623] opened 2022-07-15 14:22 UTC
### Version Information
v1.18.0

### Environment
Development

### What is the expected behaviour?

- No lint errors or warnings should be present in the code base
- CI/Lint tests should pass on PR

### What is the current behaviour?

- Number of Lint warning are present when linting is run
- CI/Lint Tests fail when run

### How to reproduce the issue?

1a. Run `npm run lint` on necessary folders within the code base (e.g `/frontend`)
1b. Review PR where CI tests are being run, and see Lint is failing 

### Screenshots or Screencast

![Screen Shot 2022-07-15 at 10 15 39 AM](https://user-images.githubusercontent.com/8715477/179242818-e9b0ca98-467b-422d-9214-a9ce8e2c7e32.png)
![Screen Shot 2022-07-15 at 10 15 59 AM](https://user-images.githubusercontent.com/8715477/179242821-df9615f9-bf15-495f-af04-5c454bc84aad.png)
![Screen Shot 2022-07-15 at 10 16 10 AM](https://user-images.githubusercontent.com/8715477/179242824-605ff4d3-eec4-4d30-950b-4bde705c7f06.png)

### Any possible solutions?

- Apply appropriate fixes for linting issues

### If the bug is confirmed, would you be willing to submit a PR?

- No

**Comment by withshubh** [comment] 2022-07-31 11:49
@arpitnath Please take a look at this issue.

**Comment by arpitnath** [comment] 2022-08-04 13:14
@Nathan-Bisson It's not a bug, some eslint issues have been introduced in the repo lately.
But thanks for raising an issue about this, we will fix it on priority.

**Comment by withshubh** [comment] 2022-08-07 20:31
fixed in #3749

**Closed by withshubh** 2022-08-07 20:31 UTC
