### ISSUE TITLE
[localization] Translate login and signup page in French

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4179] opened 2022-10-01 06:30 UTC
### Is your proposal related to a problem?

Add translations for login and signup page in French

### Describe the solution you'd like

The strings need to be translated:

![Screenshot 2022-09-30 at 3 38 25 PM](https://user-images.githubusercontent.com/25361949/193396042-65b0a71f-07f1-460b-a0fa-b59196dc3788.png)

**Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)**

**Comment by Aditya-Ambre** [comment] 2022-10-01 06:33
Hey @withshubh may I work on this issue ?

**Comment by SanjaySargam** [comment] 2022-10-01 06:33
Can U plz assign me ?

**Comment by withshubh** [comment] 2022-10-01 06:39
Hi @Aditya-Ambre , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment] 2022-10-01 06:39
Hi @SanjaySargam , 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by arushmangal** [comment] 2022-10-03 07:38
Hey, in case the person to whom the issue is already assigned is unable to solve the issue, I would gladly like to help!

**Comment by withshubh** [comment] 2022-10-03 07:41
> Hey, in case the person to whom the issue is already assigned is unable to solve the issue, I would gladly like to help!

Sure! @arushmangal 

In the meantime, you can look for other open issues with [Hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest+sort%3Aupdated-desc) tags to contribute.

**Comment by Aditya-Ambre** [comment] 2022-10-03 12:05
Hey that would be great could we set up a meeting later tonight ?

**Comment by arushmangal** [comment] 2022-10-03 14:30
Hey! I can't come to a meeting. It seems like I gave off the wrong impression. If you were a bit busy translating the document, I was proposing taking up the issue myself.

**Comment by withshubh** [comment] 2022-10-16 22:10
Hey @Aditya-Ambre 
Is there any update on it? We can assign it to someone else if you're facing any issues.

**Comment by Aditya-Ambre** [comment] 2022-10-19 08:10
I apologise for my unavailability,
I request the Issue to be assigned to another developer.
Thank You.

**Comment by celcarpe** [comment] 2022-10-22 11:04
Can I get assigned on this?

**Comment by withshubh** [comment] 2022-10-23 12:28
Hey @celcarpe 
Assigned this to you.

**Closed** 2022-10-25 03:36 UTC
Labels: good first issue, feature request, hacktoberfest, up-for-grabs
