### ISSUE TITLE
[localization] Translate App Card in German

### ISSUE THREAD

**Issue by Ambareen09** [ToolJet/ToolJet#4266] opened 2022-10-03 14:43 UTC
### Is your proposal related to a problem?

 Add translations for App Card strings in German.

### Describe the solution you'd like

The strings need to be translated:

"appCard":{
            "changeIcon":"Change Icon",
            "addToFolder":"Add to folder",
            "move":"Move",
            "to":"to",
            "selectFolder":"Select folder",
            "deleteApp":"Delete app",
            "exportApp":"Export app",
            "cloneApp":"Clone app",
            "launch":"Launch",
            "maintenance":"Maintenance",
            "noDeployedVersion":"App does not have a deployed version",
            "openInAppViewer":"Open in app viewer",
            "removeFromFolder":"Remove from folder"
        },
Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

Assign to me and I'll work on it for hacktoberfest!

**Comment by myudak** [comment] 2022-10-03 16:59
i would like to work on this

**Comment by withshubh** [comment] 2022-10-13 11:26
Hey @Ambareen09  👋 

Thanks for your interest in contributing to ToolJet. 

Closing the issue as we are only accepting localization contributions for the issues that we create unless the issue is created by the native speaker. You can always check out other open issues. 😇

**Closed by withshubh** 2022-10-13 11:26 UTC
Labels: feature request
