### ISSUE TITLE
Add text color style in text input widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4183] opened 2022-10-01 06:39 UTC
## Proposed feature
Option to change and update the text color of the text input widget with the `Text color` property in the style tab.

### Description
Currently, the text input widget only supports **Border radius**, **Visibility**, and **Disable** as style definitions.

<img width="616" alt="Screenshot 2022-10-01 at 10 19 24 AM" src="https://user-images.githubusercontent.com/67645175/193393088-1548028e-d521-42f8-b4c7-db3d96d7b6b2.png">

reference: https://github.com/ToolJet/ToolJet/pull/1721

**Comment by somenath203** [comment] 2022-10-01 06:40
Can you assign me this work please?

**Comment by arpitnath** [comment] 2022-10-01 06:41
Hi @somenath203 , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by dmdbilal** [comment] 2022-10-02 05:07
I want to work on this issue.

**Comment by dmdbilal** [comment] 2022-10-02 05:09
Which color(color code) do i need to update ?

**Comment by Navaneeth-pk** [comment] 2022-10-02 05:11
@dmdbilal The issue has an assignee, please work only on issues that are assigned to you.

**Comment by dmdbilal** [comment] 2022-10-02 05:23
Can i work on this issue now?

**Comment by Architsharma7** [comment] 2022-10-02 11:09
Hey, I would love to work on this issue, can you assign it?

**Comment by rahulsunil2** [comment] 2022-10-02 11:33
Can I work on this issue?

**Comment by trishitapingolia** [comment] 2022-10-02 13:16
Can you assign me this?

**Comment by KarthickSakthi** [comment] 2022-10-02 15:10
Can I work on this?

**Comment by MihirShinde-29** [comment] 2022-10-02 16:32
Hey, I would like to work on this issue, can you assign it to me?

**Comment by Elegidoadedo** [comment] 2022-10-02 19:27
Hello! I would like to work on this issue too

**Comment by harshit-dugar** [comment] 2022-10-03 02:53
Can I work On it @Navaneeth-pk

**Comment by Kundan1804** [comment] 2022-10-03 19:52
Hey @withshubh I am a frond end developer and would love to contribute in this issue

**Comment by withshubh** [comment] 2022-10-04 08:15
Hi @dmdbilal 👋 

We've assigned the issue to you. If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment] 2022-10-04 08:17
Hey 👋 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

cc: @Architsharma7 @rahulsunil2 @trishitapingolia @KarthickSakthi @MihirShinde-29 @Elegidoadedo @harshit-dugar @Kundan1804

**Comment by arpitnath** [comment] 2022-10-25 21:00
As @dmdbilal won't be able to continue working on this issue, unassigning the same.
cc: @withshubh 
Ref: https://github.com/ToolJet/ToolJet/pull/4302#issuecomment-1291135222

**Comment by AyushK-101** [comment] 2022-10-26 04:35
I would like to work on this, the issue assigned to me currently was already resolved

**Comment by withshubh** [comment] 2022-10-27 06:23
@AyushK-101 Assigned to you

**Comment by AyushK-101** [comment] 2022-10-27 07:01
![image](https://user-images.githubusercontent.com/86164395/198213543-c2bd2f58-5c3b-42d9-84f3-c22128f24c41.png)

@withshubh I guess this issue was already resolved

**Comment by withshubh** [comment] 2022-10-27 09:16
Thanks, @AyushK-101 

Closing this issue. cc: @arpitnath

**Closed by withshubh** 2022-10-27 09:16 UTC
Labels: good first issue, frontend, feature request, javascript, hacktoberfest, up-for-grabs, react
