### ISSUE TITLE
Password input widget: Option to customise the error message styles for validations

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4206] opened 2022-10-01 14:07 UTC
## Proposed improvement
Option to customise the error message styles for validation.

Currently, the error message color is red.
<img width="202" alt="Screenshot 2022-10-01 at 7 35 59 PM" src="https://user-images.githubusercontent.com/67645175/193413361-9c3ad743-d335-4cfd-bb91-eba80f7edd3a.png">

**Proposed improvement is the ability to change the color of the error message.**

**Comment by MuhammadAakash** [comment] 2022-10-01 14:12
Hi @arpitnath .
You mean that the user has the ability to change the color of the error message.

**Comment by arpitnath** [comment] 2022-10-01 14:14
Hi @MuhammadAakash , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by MuhammadAakash** [comment] 2022-10-01 14:17
Sure @arpitnath 
I am joining slack after it I will start working on it.

**Comment by ishani-1255** [comment] 2022-10-01 23:59
Hi @arpitnath, is there some beginner issue available to work on.

**Comment by Ruchika30** [comment] 2022-10-08 16:02
hi  @arpitnath  Kindly assign it to me too. Would like to look into as it looks like there is no update on the issue

**Comment by MuhammadAakash** [comment] 2022-10-08 21:00
@Ruchika30  am on it. I was busy the whole week.
Will do it over the weekend, and let you know.

**Comment by MuhammadAakash** [comment] 2022-10-09 06:46
Hi @Ruchika30. Please start working on this issue after confirming it from @arpitnath 
Because I don't have time. so best wishes.

**Comment by AyushK-101** [comment] 2022-10-09 07:59
Looks like the original assignee has removed his assignment. I would like to work on the issue @arpitnath if you could assign it to me.

**Comment by Ruchika30** [comment] 2022-10-09 08:19
> Hi @Ruchika30. Please start working on this issue after confirming it from @arpitnath Because I don't have time. so best wishes.

Sure . On it . Thanks for informing @MuhammadAakash . Please assign it to me @arpitnath

**Comment by prakhar-198** [comment] 2022-10-09 16:04
Is there something still left to be done? Please assign me.

**Comment by mohithgupta** [comment] 2022-10-09 18:03
I can make a PR for this. You can assign this to me if possible.

**Comment by Sanjayrk0206** [comment] 2022-10-14 05:00
Hey @arpitnath, I am interested in working on this issue. Can you assign it to me?

**Comment by Ruchika30** [comment] 2022-10-19 04:22
I am trying hard to set up the project . Dropped the message on slack as well.

**Comment by withshubh** [comment] 2022-10-26 04:07
> I am trying hard to set up the project . Dropped the message on slack as well. waiting for revert

Hey @Ruchika30 
Any luck on setting up the project?

**Comment by AyushK-101** [comment] 2022-10-26 04:33
Can I work on this?

**Comment by Ruchika30** [comment] 2022-10-26 10:43
> > I am trying hard to set up the project . Dropped the message on slack as well. waiting for revert
> 
> Hey @Ruchika30 Any luck on setting up the project?

Noo. No one ever replied to my query on slack @withshubh

**Comment by SanjoyPator1** [comment] 2022-10-26 23:22
I would love to work on this issue. Can you assign it to me?

**Comment by withshubh** [comment] 2022-10-27 06:40
> > > I am trying hard to set up the project . Dropped the message on slack as well. waiting for revert
> > 
> > 
> > Hey @Ruchika30 Any luck on setting up the project?
> 
> Noo. No one ever replied to my query on slack @withshubh

Hey @Ruchika30 - Can you please DM me on slack so that I can take a look?

**Comment by Ruchika30** [comment] 2022-10-27 09:58
> that

Okk. I have never done with docker. This is something new to me . I ll check how to install with docker

**Comment by oneknucklehead** [comment] 2022-10-30 08:07
Is the issue still up for grab?

**Comment by withshubh** [comment] 2022-10-30 16:39
> Is the issue still up for grab?

Yes, want to pick it up?

**Comment by MuhammadAakash** [comment] 2022-10-30 16:52
> > that
> 
> Okk. I have never done with docker. This is something new to me . I ll check how to install with docker

It's in the documentation that how to set up project with the docker.

**Comment by oneknucklehead** [comment] 2022-10-31 07:48
> > Is the issue still up for grab?
> 
> Yes, want to pick it up?

Yes. Joining the slack channel!

**Comment by withshubh** [comment] 2023-02-10 08:48
Unassigned @oneknucklehead since there was no update. The issue is up for grab.

**Comment by akash1520** [comment] 2023-06-01 14:13
I would like to work on this

**Comment by withshubh** [comment] 2023-06-07 06:06
Hey @akash1520 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by withshubh** [comment] 2023-06-13 08:38
Hi @Ponnada96 - My bad, the issue is already assigned to @akash1520 , I missed to update the `assignees`.

Hi @akash1520 - Any update on the pull request?

**Comment by nabeel001** [comment] 2023-06-15 17:04
hey @withshubh, I would like to work on this feature request. Can u assign this to me.

**Comment by tejakummarikuntla** [comment] 2023-06-27 07:21
Hey @nabeel001 , were you able to progress with the issues?

**Comment by nabeel001** [comment] 2023-06-27 07:26
> Hey @nabeel001 , were you able to progress with the issues?

Hey I am busy with some other work. Please assign it to someone else.

**Comment by sebabratakundu** [comment] 2023-06-28 17:51
@tejakummarikuntla can you assign me this issue?

**Comment by nabeel001** [comment] 2023-07-18 13:07
@tejakummarikuntla Im now available to work on this issue and have also built the requested feature in my local setup.
Kindly reassign me this issue and I'll immediately send the pull request for the same.

**Comment by nabeel001** [comment] 2023-08-12 10:07
@tejakummarikuntla, @arpitnath, @withshubh, can u pls assign this issue to me.

**Comment by blank0537** [comment] 2024-01-15 14:25
@withshubh @arpitnath Please merge this PR #8578 . Let me know if any modifications are required.

**Comment by PriteshKiri** [comment] 2024-06-17 06:37
Closing the issue as it is resolved!

**Closed by PriteshKiri** 2024-06-17 06:37 UTC
Labels: good first issue, feature request, up-for-grabs
