### ISSUE TITLE
Imported app doesn't loads the latest version on app editor

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#3431] opened 2022-06-29 08:28 UTC
### What is the expected behaviour?

When importing the app, the latest version should be loaded. Suppose there are 4 versions in an app v1, v2, v3, v4, and v4 is the latest and the released version then when this app is exported and then imported to the same/another workspace it should load the v4 when opened in the app editor(edit mode)

### What is the current behaviour?

When importing the app, the latest version should be loaded in when opened in the app editor.

### How to reproduce the issue?

1. Build an app with multiple versions(release the last version)
2. export and then import the app
3. Edit it and check the loaded version

### Screenshots or Screencast

https://user-images.githubusercontent.com/25361949/176388926-e3d2f791-d3ca-4fa4-982f-e33534c00913.mp4

**Comment by NoahMLoomis** [comment] 2022-07-06 17:17
Could not reproduce, tried with 3 different versions, then 4. Both times after importing the latest version was displayed first

**Comment by NoahMLoomis** [comment] 2022-07-06 19:04
@withshubh sorry for being unclear, I did I wasn't able to reproduce while having the 4th version released. It was still the 4th (released) version that was being loaded up first on import

**Comment by akshaysasidrn** [comment] 2022-09-28 06:55
Fixed in #4117

**Closed** 2022-09-28 06:56 UTC
Labels: bug, good first issue, up-for-grabs
