### ISSUE TITLE
Set character limit to Page name

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6744] opened 2023-06-15 10:13 UTC
Currently, the Pages do not hold a limit to the number of characters in their name.
Restrict the number of characters to `50` in the page name.

<img width="558" alt="Screenshot 2023-06-15 at 3 42 20 PM" src="https://github.com/ToolJet/ToolJet/assets/34749692/d8d14624-12d1-4fcb-b4e9-fc8e662241bd">

**Comment by IshaanAdarsh** [comment] 2023-06-15 10:24
I’ll do this.
could you assign this to me.

**Comment by tejakummarikuntla** [comment] 2023-06-15 14:28
Thanks for you intrest @IshaanAdarsh , and @Ar-Akhil. 

Hey @IshaanAdarsh, given the issue is tagged with `good first issue` let's welcome the first-time contributors.
Kindly explore the issues that are only tagged with `up for grabs`, Ishaan and looking forward to get your latest PR merged. Thanks for your understanding/

Assigned this issue to @Ar-Akhil .

**Comment by Ar-Akhil** [comment] 2023-06-15 17:18
hey @tejakummarikuntla thanks for assign. But it seems like the issue is already solved and the character limit is set to 25 chars.
Do point me in the right direction if i am wrong

**Comment by tejakummarikuntla** [comment] 2023-08-09 06:19
Hey @Ar-Akhil , Sorry for the delay in response.

The issue was not addressed yet; the requirement is to add a character limit to the page name. Let us know if you'd still be able to take up the issue.

**Comment by tejakummarikuntla** [comment] 2023-08-28 18:49
Unassigned due to contributor activity.

**Comment by ValkonX33** [comment] 2023-08-31 12:47
can you assign me this?

**Comment by YashuaPervez** [comment] 2023-09-02 02:16
Hi @tejakummarikuntla,
I would like to take this issue.

**Comment by tejakummarikuntla** [comment] 2023-09-25 10:58
Hey @YashuaPervez , sorry for missing out the comment, are you interested to get this assigned to you?

**Comment by JaswanthJeethu18** [comment] 2023-09-30 17:03
Its an easy fix ! i can do it , it would help me a lot if you assign me this issue

**Comment by tejakummarikuntla** [comment] 2023-09-30 18:17
Thanks for your interest @JaswanthJeethu18, Assigned the issue to you. To seek assistance or resolve issues, you can join our community at [Slack](https://tooljet.com/slack).

**Closed** 2023-12-29 09:33 UTC
Labels: enhancement, good first issue, up-for-grabs
