### ISSUE TITLE
[docs]: rename Workspace Environment Variables to Workspace Variables 

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4289] opened 2022-10-04 09:41 UTC
### Summary

rename `Workspace Environment Variables` to `Workspace Variables`

### Issue Type

Documentation bug

### The entire URL of the documentation with the issue

https://docs.tooljet.com/docs/tutorial/workspace-environment-variables/

### If the issue is confirmed, would you be willing to submit a pull request?

No

### Code of Conduct

- [X] I agree to follow the ToolJet Code of Conduct

**Comment by Syed-Ansar** [comment] 2022-10-04 09:42
can you assign it me, I want to work on this ?

**Comment by HVbajoria** [comment] 2022-10-04 09:46
Hello, 
So as I understand we need to update the doc by renaming Workspace Environment Variables to Workspace Variables wherever it's present in the doc to which this link refers to?
Could you please guide me if I am right? And assign me so that I may work on it?

**Comment by MrKrishnaAgarwal** [comment] 2022-10-04 10:13
@withshubh Please assign this to me, I have already made the PR #4290

**Comment by Navaneeth-pk** [comment] 2022-10-04 10:37
@MrKrishnaAgarwal please follow the rules. You should work only on issues that are assigned to you. We will mark all other PRs as invalid.

**Comment by MrKrishnaAgarwal** [comment] 2022-10-04 10:39
> @MrKrishnaAgarwal please follow the rules. You should work only on issues that are assigned to you. We will mark all other PRs as invalid. 

Ohh okay
I didn't knew that, I am a first time contributor in this repository
What should I do now?

**Comment by withshubh** [comment] 2022-10-04 12:15
> renamed Workspace Environment Variables to Workspace Variables #4290

Yes @HVbajoria You're correct.

Let's assign this issue to @MrKrishnaAgarwal since he has already created a PR for this issue. Also, @MrKrishnaAgarwal Please follow the [contributing guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) otherwise we will have to mark the PRs `invalid` which will affect your hacktoberfest contribution.

**Comment by MrKrishnaAgarwal** [comment] 2022-10-04 13:00
> > renamed Workspace Environment Variables to Workspace Variables #4290
> 
> Yes @HVbajoria You're correct.
> 
> Let's assign this issue to @MrKrishnaAgarwal since he has already created a PR for this issue. Also, @MrKrishnaAgarwal Please follow the [contributing guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) otherwise we will have to mark the PRs `invalid` which will affect your hacktoberfest contribution.
> 

Sure, I will not let this happen again
Sorry :(

**Comment by AbhishekTiwari23** [comment] 2022-10-07 18:34
If the issue is still going on, then please let me know. I want to contribute.

**Comment by MrKrishnaAgarwal** [comment] 2022-10-08 01:46
> If the issue is still going on, then please let me know. I want to contribute.

I am already assigned and I have already made a PR.

**Comment by prakhar-198** [comment] 2022-10-09 16:05
Is there still something left to be done? please assign me I'll fix it!

**Comment by MrKrishnaAgarwal** [comment] 2022-10-09 16:48
> Is there still something left to be done? please assign me I'll fix it!

I have already made a PR, please look for some other issues, Thanks

**Closed** 2022-10-10 02:42 UTC
Labels: documentation, good first issue, hacktoberfest, up-for-grabs
