### ISSUE TITLE
The default text color value for the button widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4243] opened 2022-10-03 06:47 UTC
### Environment
Latest `develop`

### What is the expected behaviour?
The default text color value for the button widget should be set to `#fff`

### What is the current behaviour?
The default value is not set for the text color style definition.

### How to reproduce the issue?

1. Drop a Button widget into the editor
2. Open the widget inspector and navigate to the **styles** tab

### Any possible solutions?

**Source**: `frontend/src/Editor/WidgetManager/widgetConfig.js` ~ **Line 486**
**Solution**
```
      styles: {
        textColor: { value: '#fff' },
        ...
      },
```

**Comment by Aman0786-git** [comment] 2022-10-03 06:52
Can you assign this to me

**Comment by arpitnath** [comment] 2022-10-03 07:12
Hi @Aman0786-git , 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Candida18** [comment] 2022-10-03 13:08
Can you pls assign this issue to me? I'll be happy to work on it

**Comment by abhishekpatil4** [comment] 2022-10-04 16:22
@arpitnath Assign me this task ,will get it done in no time

**Comment by daniloff200** [comment] 2022-10-04 17:42
I've added the fix, @arpitnath , can it marked as a my task to work on?

**Comment by arpitnath** [comment] 2022-10-04 22:22
@daniloff200 You are supposed to get the issue assigned to you first before raising pull requests.
Unassigned PRs will be considered invalid and spam or invalid tags will be added.

**Comment by arpitnath** [comment] 2022-10-04 22:23
We have to assign the issue to the first person who expressed interest. 
Assigning the task to @abhishekpatil4.

You can check out other open issues here: https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest.

**Comment by abhishekpatil4** [comment] 2022-10-05 11:33
@arpitnath Please verify my pull request, and suggest if any changes needed

**Comment by Candida18** [comment] 2022-10-06 03:35
Can you pls assign this issue to me
I'll make the changes in a few minutes

The pull request added by @abhishekpatil4 didn't pass the checks.

**Comment by Navaneeth-pk** [comment] 2022-10-06 03:37
@Candida18 please do not spam by copying and pasting irrelevant comments. The issue is assigned and already have a PR.

**Comment by mohdhaider07** [comment] 2022-10-06 17:12
@arpitnath can you please assign any  good first issue

**Comment by withshubh** [comment] 2022-10-07 07:01
> @arpitnath can you please assign any good first issue

Hey @mohdhaider07 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by withshubh** [comment] 2022-10-09 08:16
> @withshubh Can you please verify my pull request, and suggest if any changes needed

Hey @abhishekpatil4 👋  - The PR will be reviewed soon.

**Comment by abhishekpatil4** [comment] 2022-10-13 05:06
@withshubh @arpitnath I've done the suggested changes, please verify my pull request

**Closed** 2022-10-13 15:23 UTC
Labels: bug, frontend, javascript, hacktoberfest, up-for-grabs
