### ISSUE TITLE
[Accessibility]: Elements don't have sufficient contrast

### ISSUE THREAD

**Issue by Pranay-Tej** [ToolJet/ToolJet#5018] opened 2022-12-19 15:40 UTC
### Version Information
- 1.30.0

### Environment
- Windows (develop)

### What is the expected behaviour?
- Elements should have sufficient contrast between foreground and background colors.

### What is the current behaviour?
- Elements don't have sufficient contrast in both light mode and dark mode.

### How to reproduce the issue?

1. Install "Accessible Web Helper" extension: https://chrome.google.com/webstore/detail/accessible-web-helper/gdnpkbipbholkoaggmlblpbmgemddbgb
2. Scan the page with extension
3. Click on "Highlight All elements" under "Elements must have sufficient color contrast" section
4. Inspect the elements with devtools (Ctrl+Shift+C)
5. Inspect the color in dev tools styles section (Refer to screenshots)

### Screenshots or Screencast

- Dasboard
![image](https://user-images.githubusercontent.com/34662441/208459208-b6467aeb-651a-40fe-8b62-0c38f73ab430.png)
![image](https://user-images.githubusercontent.com/34662441/208458130-df744983-6304-42ad-bbb3-9754736a2213.png)
![image](https://user-images.githubusercontent.com/34662441/208458627-ac1e8392-0fe4-4d5b-9347-5e635feedd96.png)
![image](https://user-images.githubusercontent.com/34662441/208459673-8bcdc6c1-4633-4296-bcbf-2a67fc364186.png)

- Editor
![image](https://user-images.githubusercontent.com/34662441/208459897-1eda2fa0-eb28-4ea1-a1fa-84679d328d4b.png)
![image](https://user-images.githubusercontent.com/34662441/208460171-e6c6a7f7-e387-49a5-9633-33b491f2d879.png)

### Any possible solutions?
- Adjust the color system to ensure text has enough contrast with the background

### Can you identify the location in the driver source code where the problem exists?
- Design/CSS color system

### If the bug is confirmed, would you be willing to submit a PR?
- This may require changes in the design system

**Comment by withshubh** [comment] 2022-12-21 09:47
Hey @Pranay-Tej - Thanks for creating the issue.
Closing this issue as this is not a bug, and we are also working on UI redesign at the moment.

**Closed by withshubh** 2022-12-21 09:47 UTC
Labels: bug
