### ISSUE TITLE
Set a default country code on onboarding form

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#6437] opened 2023-05-17 09:08 UTC
### What is the current behaviour?
On onboarding form for new users, the country code dropdown is blank on the mobile number page. 

Fix the issue by setting a default country code in the dropdown.

### Steps to reproduce
- Sign up on ToolJet: https://www.tooljet.com/signup
- Open the link received on your registered email
- The onboarding form will open up, on the last step user is asked to enter phone number 

### Screenshots or Screencast
![image (12)](https://github.com/ToolJet/ToolJet/assets/25361949/ea660cbc-9e8e-4509-9d4e-c1c9e30810af)

**Comment by FourAndHalf** [comment] 2023-05-17 11:38
As far as i looked it up, the only change needed is to change the useState condition in function OnBoardingForm

```js
function OnBoardingForm({ userDetails = {}, token = '', organizationToken = '', password, darkMode }) {
  const Logo = darkMode ? LogoDarkMode : LogoLightMode;
  const [page, setPage] = useState(0);
  const [completed, setCompleted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [formData, setFormData] = useState({
    companyName: '',
    role: '',
    companySize: '',
```
```diff
-phoneNumber: '',
+phoneNumber: '+1',
```
```js
  });
```

if you think this may solve the problem, can you assign this issue to me.

**Comment by withshubh** [comment] 2023-05-17 13:48
The change is required in these two files.
![Screenshot 2023-05-17 at 2 33 36 PM](https://github.com/ToolJet/ToolJet/assets/25361949/2ea43ebb-4436-49aa-a142-aaf5f5be4a42)

**Comment by wasimTQ** [comment] 2023-05-17 18:13
@withshubh Instead of hardcoding values. Should we use [country.is/](https://country.is/) api and put the user's country in the `PhoneInput`?

**Comment by CVamsi27** [comment] 2023-05-18 05:33
> @withshubh Instead of hardcoding values. Should we use [country.is](https://country.is/) api and put the user's country in the `PhoneInput`?

I would like to work in this.

**Comment by iSatVeerSingh** [comment] 2023-05-29 14:07
@FourAndHalf I tried your fix and as we can see that your fix is not working. Here is a screenshot below.


![Screenshot from 2023-05-29 19-25-56](https://github.com/ToolJet/ToolJet/assets/85070570/8ef2461f-aa31-4faa-a1fa-3171f2f7ed39)

I found the solution for this and I am working on it.

**Comment by Navaneeth-pk** [comment] 2023-05-29 14:11
@iSatVeerSingh The issue is already assigned to someone and they are working on it. Please follow the contributing guide.

**Comment by iSatVeerSingh** [comment] 2023-05-29 14:20
@FourAndHalf You can pass a country prop to PhoneInput component to set a default country.

**Comment by FourAndHalf** [comment] 2023-05-30 02:23
@iSatVeerSingh  ok I will try passing through a country prop in phoneInput component, and thanks for the feedback

**Comment by FourAndHalf** [comment] 2023-05-31 06:24
The pull request has been changed according to the problems pointed out by the maintainer

**Closed** 2023-06-15 11:04 UTC
Labels: enhancement, good first issue, up-for-grabs
