### ISSUE TITLE
The default text color value should be set to `#000` for table widget

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4242] opened 2022-10-03 06:42 UTC
### Environment
Latest `develop`

### What is the expected behaviour?
The default text color value should be set to `#000` when table is dropped for the first time.

### What is the current behaviour?
The default value is not set for the text color style definition.

### How to reproduce the issue?

1. Drop a Table widget to the editor
2. Open the widget inspector and navigate to the **styles** tab

### Any possible solutions?

**Source**: `frontend/src/Editor/WidgetManager/widgetConfig.js` ~ **Line 354**
**Solution**
```
      styles: {
        textColor: { value: '#000' },
        ...
      },
```

**Comment by PaarthAgarwal** [comment] 2022-10-03 06:43
Please assign it to me

**Comment by kushal-gopal** [comment] 2022-10-03 06:44
Can I take this up, thanks!

**Comment by PaarthAgarwal** [comment] 2022-10-03 07:14
Opened a PR for same

> Please assign it to me

**Comment by withshubh** [comment] 2022-10-03 07:16
Hey @PaarthAgarwal 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you because you commented first but from the next time please don't create the PR unless the issue is assigned to you. This might lead to adding `spam` or `invalid` tag on the PR which will affect your Hacktoberfest contributions.

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by withshubh** [comment] 2022-10-03 07:17
Hey @kushal-gopal 👋 

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

**Comment by PaarthAgarwal** [comment] 2022-10-03 07:35
> Hey @PaarthAgarwal 👋
> 
> Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you because you commented first but from the next time please don't create the PR unless the issue is assigned to you. This might lead to adding `spam` or `invalid` tag on the PR which will affect your Hacktoberfest contributions.
> 
> If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

Thanks. I'll keep that in mind. I don't create any PR unless I am assigned to that issue or I haven't been the first commentor

**Comment by kushal-gopal** [comment] 2022-10-04 13:49
Hi, I thought I was assigned this issue?

**Comment by Candida18** [comment] 2022-10-06 03:35
Can I please work on this issue?
I'll make the changes in no time.

The pull request added by @PaarthAgarwal didn't pass the checks.

**Closed** 2022-10-10 02:44 UTC
Labels: bug, good first issue, javascript, hacktoberfest, up-for-grabs, widget
