### ISSUE TITLE
[localization] Translate Confirmation Page strings to French

### ISSUE THREAD

**Issue by arushmangal** [ToolJet/ToolJet#4353] opened 2022-10-08 04:48 UTC
### Is your proposal related to a problem?
Add translations for Confirmation Page strings in French.

### Describe the solution you'd like
Add translations for Confirmation Page strings in French:

![Annotation 2022-10-08 101807](https://user-images.githubusercontent.com/83538403/194688945-4cd8e965-d568-49bb-877d-0f9bdefc06d0.jpg)

### If the feature is approved, would you be willing to submit a PR?
Yes

**Comment by Frenchtoast0** [comment] 2022-10-08 07:35
I would be interested in doing this one.

**Comment by withshubh** [comment] 2022-10-13 11:24
Hey @arushmangal 👋 

Thanks for your interest in contributing to ToolJet. 

Closing the issue as we are only accepting localization contributions for the issues that we create unless the issue is created by the native speaker. You can always check out other open issues. 😇

**Closed by withshubh** 2022-10-13 11:24 UTC
Labels: feature request
