### ISSUE TITLE
Problem while running the localhost

### ISSUE THREAD

**Issue by SaunakNandi** [ToolJet/ToolJet#10951] opened 2024-10-12 11:04 UTC
### Environment
    Linux

### What is the expected behaviour?
The page should load the actual content

### What is the current behaviour?
While running on port 8082 I am not able to see the result

### Screenshots or Screencast
![Screenshot-3](https://github.com/user-attachments/assets/13a7d208-ca4c-4a38-9317-dca93ef03560)

### Please provide any traces or logs that could help here.
To run the application I used this code ->

cd ./plugins && npm start
cd ./server && npm run start:dev
cd ./frontend && npm start

**Comment by PriteshKiri** [comment] 2024-10-14 12:45
Hey @SaunakNandi,

Can you please drop this query in the contributor's channel of our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) 

The team will help you resolve this. It's not a bug but some issue with some configuration while setting up. Thus closing the issue.

**Closed by PriteshKiri** 2024-10-14 12:45 UTC
Labels: bug
