### ISSUE TITLE
Maintain column widths of dynamically generated columns if an `id` is supplied

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#8507] opened 2024-01-05 13:19 UTC
### Is your proposal related to a problem?

Presently, the column width of dynamically generated columns on Table component, when they are modified by user by dragging on the Table UI, are not maintained over page refresh

### Describe the solution you'd like

It should be maintained.

**Comment by kavinvenkatachalam** [comment] 2024-01-30 08:21
Closing this as it is a duplicate of #8524

**Closed by kavinvenkatachalam** 2024-01-30 08:21 UTC
Labels: feature request, roadmap, appbuilder, Table component
