### ISSUE TITLE
widget crashes when an object is set as label property

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4959] opened 2022-12-13 06:38 UTC
### What is the current behaviour?

Widget with `label` property such as toggle or dropdown and many others show `something went wrong` when an object `{{{}}}` is set as their `label` value

### What is the expected behaviour?

On setting the `{{{}}}` object as label should display the object label

### How to reproduce the issue?

1. add toggle/dropdown or any other component having label property on to the canvas
2. edit the `label` property and set value as `{{{}}}`
3. click any where on the canvas and the widget will break

### Screenshots or Screencast

<img width="683" alt="Screenshot 2022-12-13 at 12 03 34 PM" src="https://user-images.githubusercontent.com/25361949/207244371-060442ba-fa3a-4862-a5fb-8e6d459d28f5.png">

**Comment by Sheikh-JamirAlam** [comment] 2022-12-15 05:45
Can you explain the issue?
Currently it shows "Something went wrong." when label is set to {{{}}} .
What should be the expected behaviour?

**Comment by withshubh** [comment] 2022-12-15 06:04
> Can you explain the issue? Currently it shows "Something went wrong." when label is set to {{{}}} . What should be the expected behaviour?

My bad, I just updated the issue description.

- What is the current behaviour?
	- Widget with label property such as toggle or dropdown and many others show something went wrong when an object {{{}}} is set as their label value

- What is the expected behaviour?
	- On setting the {{{}}} object as label should display the object label

**Comment by withshubh** [comment] 2022-12-26 06:24
Hey @Sheikh-JamirAlam - Are you still working on it?

**Comment by Sheikh-JamirAlam** [comment] 2022-12-26 06:42
No I did not work on this.

**Comment by withshubh** [comment] 2022-12-26 06:49
> @withshubh I did not work on this.

@Sheikh-JamirAlam Do let us know if you want to work on this or we can assign it to someone else.

**Comment by Sheikh-JamirAlam** [comment] 2022-12-26 08:56
@withshubh No not working on this, you can assign it to someone else.

**Comment by lokeswaran-aj** [comment] 2023-02-18 16:45
Hi, @withshubh 
I could not reproduce the bug. Is this fixed?
<img width="603" alt="Screenshot 2023-02-18 at 10 14 03 PM" src="https://user-images.githubusercontent.com/74011196/219877670-6b153bfd-1671-411e-a8fb-3504b8fe8a49.png">

**Comment by illiteratewriter** [comment] 2023-02-21 06:35
This particular issue got resolved with #5265, I think.

**Closed** 2023-03-03 10:59 UTC
Labels: bug, good first issue, up-for-grabs
