### ISSUE TITLE
dev local start server connect to database fail 

### ISSUE THREAD

**Issue by oliver-xie666** [ToolJet/ToolJet#4707] opened 2022-11-04 03:57 UTC
### Environment

   window

### What is the expected behaviour?

  connect to database

### What is the current behaviour?

  connect to database fail

### How to reproduce the issue?

1.cd server folder npm run db:create
2.
3.

### Screenshots or Screencast

 this is my .env file 
![image](https://user-images.githubusercontent.com/75602879/199882344-b7c58090-1f42-4872-a568-7a8467ef0b67.png)
npm run
  ![image](https://user-images.githubusercontent.com/75602879/199882141-ed947f7b-fe91-4f4d-98c2-9021ffb01037.png)

**Comment by withshubh** [comment] 2022-11-10 12:38
Hey @oliver-xie666 - Closing this issue as this is not a bug but related to the error in setting up ToolJet. 
In windows, we recommend using WSL2 and use the [ubuntu setup doc](https://docs.tooljet.com/docs/contributing-guide/setup/ubuntu). You can join our [Slack community](https://www.tooljet.com/slack) and drop your questions there if you need help setting up ToolJet.

**Closed by withshubh** 2022-11-10 12:38 UTC
Labels: bug
