### ISSUE TITLE
In new version dropdown, default select current version

### ISSUE THREAD

**Issue by jibe-b** [ToolJet/ToolJet#5852] opened 2023-03-27 13:30 UTC
When creating a new version, the default selected upstream version is the first created version.

![image](https://user-images.githubusercontent.com/6146483/227951438-9047d64f-99e7-4a15-9f0c-d48310310a27.png)

It would save a few clicks that the default selected version be the current version (not the last created but the "editingVersiong").

**Comment by shubh22** [comment] 2023-03-28 10:59
Duplicate #5732

**Comment by withshubh** [comment] 2023-04-04 09:37
Hey @jibe-b - Thanks for creating the issue. Closing this one as this is a duplicate of #5732.

**Closed by withshubh** 2023-04-04 09:37 UTC
Labels: feature request, valid
