### ISSUE TITLE
Layout accordion of widget inspector in Custom widget should be open by default

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4239] opened 2022-10-03 06:32 UTC
### What is the expected behaviour?
Layout accordion of widget inspector in Custom Component should be open by default

### What is the current behaviour?
By default, it is closed.

### How to reproduce the issue?

1. Drop a Custom widget
2. Open the widget inspector
3. On the property tab, the Layout accordion is closed by default

ref: https://github.com/ToolJet/ToolJet/pull/4024/files#diff-56125a6db3222d10ff566ab146e36e1b56b08c5fd8dd8fb5cb8b5eb09afd1281

**Comment by PaarthAgarwal** [comment] 2022-10-03 06:33
I want to work on it. Assign it to me please

**Comment by PaarthAgarwal** [comment] 2022-10-03 07:28
This issue appears similar to the one I submitted a PR earlier. Let me know if that's the right way and I'll do the same for it too

**Comment by alammoiz** [comment] 2022-10-03 08:52
Please assign to me @arpitnath

**Comment by mohithgupta** [comment] 2022-10-09 18:05
Can you provide a screenshots for reproducing the issue ? Then you can assign this to me if possible!

**Comment by alammoiz** [comment] 2022-10-11 13:36
@arpitnath could you please assign to me this?

**Comment by withshubh** [comment] 2022-10-26 04:10
> Can you provide a screenshots for reproducing the issue ? Then you can assign this to me if possible!

Hey @mohithgupta 
Are you still interested in this issue?

**Comment by AyushK-101** [comment] 2022-10-28 13:05
![image](https://user-images.githubusercontent.com/86164395/198597670-c6daa71f-6bd4-4682-b848-ab14f791bd15.png)


@withshubh @arpitnath I guess the issue is already resolves, the layout accordion is open

**Comment by AyushK-101** [comment] 2022-10-28 13:11
@arpitnath @withshubh can I work on this? Also, how to make a custom widget? The issue currently assigned to me is no more there in the current version(Amazon SES logo) and I've made a PR for the dark mode dropdown issue.

**Comment by withshubh** [comment] 2022-10-30 16:17
> @arpitnath @withshubh can I work on this? Also, how to make a custom widget? The issue currently assigned to me is no more there in the current version(Amazon SES logo) and I've made a PR for the dark mode dropdown issue.

Please create a PR for `Amazon SES logo` fix first.

**Comment by zehan12** [comment] 2023-04-25 18:38
@arpitnath @withshubh can you assign this task to me.

**Comment by withshubh** [comment] 2023-04-27 14:24
Hey @zehan12 - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by sebabratakundu** [comment] 2023-06-10 15:01
Hi @withshubh, since there is no activity on this issue, can you assign this to me?

**Comment by withshubh** [comment] 2023-06-21 10:25
Hey @sebabratakundu - Thanks for showing interest in contributing to ToolJet. Assigned the issue to you.

**Comment by sebabratakundu** [comment] 2023-06-25 13:36
Hi @withshubh, I opened a PR for this issue, please let me know if anything is missing.

**Closed** 2023-07-03 11:52 UTC
Labels: bug, good first issue, up-for-grabs
