### ISSUE TITLE
No clear indication for which options are selected in multi-select widget.

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#1580] opened 2021-12-15 06:59 UTC
### What is the expected behaviour?
There should be some kind of indication while options are selected. For eg two options are selected then there should be some indication that those 2 particular options are selected.

### What is the current behaviour?

It does not have any indication while any option is selected.

### How to reproduce the issue?

1. Drag and drop multi-select 
2. Click on select and select multiple values.
3. Observe

### Screenshots or Screencast
https://drive.google.com/file/d/1vYfuEYjULdcfHErLhfAYF2ZtkLBVSkCv/view?usp=sharing

**Comment by withshubh** [comment] 2022-08-22 05:53
Closing as the issue is fixed

**Closed** 2022-08-22 05:53 UTC
Labels: bug, widget
