### ISSUE TITLE
[fr] Allow Custom Component to read global variables and other component data

### ISSUE THREAD

**Issue by bestpika** [ToolJet/ToolJet#4312] opened 2022-10-05 08:39 UTC
### Is your proposal related to a problem?

I want to read the relevant data directly.

### Describe the solution you'd like

In the Custom Component example, I found that ToolJet will bind data, updateData and runQuery to the component, so is it possible to bind components and global variables as well?

```js
const MyCustomComponent = ({data, updateData, runQuery}) {...}
```
↓
```js
const MyCustomComponent = ({data, updateData, runQuery, variables, components}) {...}
```

**Comment by Candida18** [comment] 2022-10-06 16:32
Can I work on this?

**Comment by vedant-z** [comment] 2022-10-07 05:12
@bestpika If this is confirmed may I work on this please?

**Comment by arpitnath** [comment] 2022-10-07 14:16
Hi @Candida18 and @bestpika, Thanks for showing interest in contributing to ToolJet.

@Candida18 You should raise a Pull Request only when the issue is assigned to you by the core team.
Ignoring, for the first time, and assigning the issue to you.

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)
Happy hacking 🚀

**Comment by Candida18** [comment] 2022-10-07 15:39
Sorry for the mistake. Could you please review the PR? @arpitnath 
Thank you!

**Comment by kavinvenkatachalam** [comment] 2022-10-10 08:36
@bestpika Instead of passing additional props to the custom component, the requirement can be achieved by passing it to the data props. Attaching the same data for your reference and closing the issue

`{{{ title: 'Hi! There', buttonText: 'Update Title', customVariable: variables}}}`

You can use the `data.customVariable` inside the custom component to get global variables access. The component data can be passed in a similar way.

**Closed by kavinvenkatachalam** 2022-10-10 08:36 UTC
Labels: feature request

**Comment by bestpika** [comment] 2022-10-13 20:44
I actually tried passing variables in directly, but because of #4347, I couldn't access the variables properly.
