### ISSUE TITLE
It shows horizontal scrollbar when hover.

### ISSUE THREAD

**Issue by sanketshinde3001** [ToolJet/ToolJet#10867] opened 2024-10-02 17:26 UTC
### Environment
Windows 11

### What is the expected behaviour?
When hover it should not show any scrollbar. It only stop that motion.

### What is the current behaviour?
It showing the horizontal scrollbar.

### Screenshots or Screencast
https://github.com/user-attachments/assets/4f526e96-3b36-4f50-a21f-e0a05d387d43

### If the bug is confirmed, would you be willing to submit a PR?
Yes. I'm interested.

**Comment by Hrithikshetty** [comment] 2024-10-03 03:41
hello can you assign this to me..!

**Comment by Jagss24** [comment] 2024-10-03 05:01
@sanketshinde3001  I don't think it's a bug, it's a feature to scroll horizontally through it.

**Comment by sanketshinde3001** [comment] 2024-10-03 05:30
@Jagss24 No man 😅. This is not a feature at all.

**Comment by Jagss24** [comment] 2024-10-03 10:51
I think its not a bug. But it just doesn't look good you can hide the horizontal scrollbar but the user should be able to move scroll through it.

**Comment by Mefisto04** [comment] 2024-10-05 14:30
Hi @sanketshinde3001 ,

I noticed that the carousel is displaying a horizontal scrollbar on hover. The expected behavior is that the motion should pause without showing the scrollbar. Please assign this issue to me, and I'll resolve it.

**Approach:**
- Ensure the carousel's motion pauses without triggering unnecessary scrollbars by adjusting the container's dimensions and scrolling behavior.

**Comment by sanketshinde3001** [comment] 2024-10-05 17:22
@Mefisto04  Create your own issue man..

**Comment by sanketshinde3001** [comment] 2024-10-07 08:36
@PriteshKiri Hii , can you please check this issue.

**Comment by PriteshKiri** [comment] 2024-10-07 10:09
Hey @sanketshinde3001,

Thanks for opening this issue! Unfortunately, website-related issues are not open for community contributions. Only issues with the `community contribution` label are available for contributions.

Our internal team will take care of this one.

**Closed** 2024-10-08 04:30 UTC
Labels: bug
