### ISSUE TITLE
On hover, the background color of the button widget should be 15-20% darker than the baseline provided.

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#4237] opened 2022-10-03 06:17 UTC
### Environment
Latest `develop`

### What is the expected behaviour?
On hover, the background color of the button widget should be 15-20% darker than the baseline provided.

### What is the current behaviour?
On hover, the background color of the widget turns transparent.

### How to reproduce the issue?

1. Drop a Button widget to the editor
2. Hover on the widget

### Screenshots or Screencast
<img width="420" alt="Screenshot 2022-10-03 at 11 46 04 AM" src="https://user-images.githubusercontent.com/67645175/193512180-87e7576c-0838-4b99-b58b-016f410f8c5a.png">

### Any possible solutions?

**Source**: `frontend/src/Editor/WidgetManager/widgetConfig.js` ~ **Line 485**
**Solution**
```
      styles: {
        backgroundColor: { value: **'#375FCF'** },
        ...
      },
```

**Comment by PaarthAgarwal** [comment] 2022-10-03 06:19
Please assign it to me

**Comment by iamakhileshmishra** [comment] 2022-10-03 07:19
I would love to contribute in this please assign this to me @arpitnath

**Comment by withshubh** [comment] 2022-10-03 07:42
Hey @iamakhileshmishra 👋 

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Kundan1804** [comment] 2022-10-03 19:51
Hey @withshubh  I am a frond end developer and would love to contribute in this issue

**Comment by AbhishekTiwari23** [comment] 2022-10-07 18:35
If this issue is still going on, then please let me know. I want to contribute

**Comment by withshubh** [comment] 2022-10-09 08:21
Hey @iamakhileshmishra - Any updates on the PR?

**Comment by withshubh** [comment] 2022-10-25 11:22
Unassigned @iamakhileshmishra as there was no update on it.

**Comment by withshubh** [comment] 2022-10-26 04:05
Hey @AbhishekTiwari23 
Are you still interested in this issue?

**Comment by AyushK-101** [comment] 2022-10-26 04:30
![image](https://user-images.githubusercontent.com/86164395/197934816-566ef9a4-8c8d-4aff-a800-ac5ab87cdd7a.png)

@withshubh I guess the issue has been already resolved

**Comment by iamakhileshmishra** [comment] 2022-10-26 09:23
Sorry @withshubh Sorry, Due to my academic work I was not able to work on the issue assigned to me, I am guilty of such behaviour. 
If this issue is still not resolved I would love to complete my work.

**Comment by SanjoyPator1** [comment] 2022-10-26 23:22
I would love to work on this issue. Can you assign it to me?

**Comment by withshubh** [comment] 2022-12-12 11:40
Closing as the issue is fixed.

**Closed by withshubh** 2022-12-12 11:40 UTC
Labels: bug, good first issue, frontend, javascript, hacktoberfest, up-for-grabs, react
