### ISSUE TITLE
Workspace Constants: The text in the middle of the page should be updated from "Use Workspace constants seamlessly in both the app builder and global data source connections across ToolJet." to "Use workspace constants seamlessly in both the app builder and global data source connections across ToolJet."

### ISSUE THREAD

**Issue by ShazanRizvi** [ToolJet/ToolJet#7335] opened 2023-08-26 07:12 UTC
### Description

Upon accessing the workspace settings tab and navigating to the Workspace Constants section within the side menu bar, if no workspace constants have been added to the specific workspace, a text is displayed as follows: "Use Workspace constants seamlessly in both the app builder and global data source connections across ToolJet." This text should be revised to: "Use workspace constants seamlessly in both the app builder and global data source connections throughout ToolJet."

### Steps to Reproduce:

1. Navigate to the ToolJet application.
2. From the left sidebar displaying the icons click on the icon that shows the tooltip as "Workspace Settings".
3. A new sidebar is shown on this page which has the option of "Workspace Constants".
4. Click on it and observe the text in the middle of the page.

### Expected Output:
The text "Use Workspace constants seamlessly in both the app builder and global data source connections across ToolJet." needs to be updated to "Use workspace constants seamlessly in both the app builder and global data source connections across ToolJet."

<img width="1408" alt="Screenshot 2023-08-26 at 12 35 30 PM" src="https://github.com/ToolJet/ToolJet/assets/85864291/e4e1e74f-1d31-4497-9733-11048e323d66">

**Comment by subhajit20** [comment] 2023-08-26 14:04
@ShazanRizvi  made a pr https://github.com/ToolJet/ToolJet/pull/7336

**Comment by tejakummarikuntla** [comment] 2023-08-28 18:12
Hello @subhajit20 ,
I would like to kindly request you to review the [contributor guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) and ensure that you raise pull requests (PRs) for the issues assigned specifically to you. Since there's already an issue assigned to you, I encourage you to explore up-for-grabs labeled issues, and please comment on your interest in assigning. Thank you for your understanding, and I look forward to your continued involvement in the project.

**Comment by subhajit20** [comment] 2023-08-28 18:24
> Hello @subhajit20 , I would like to kindly request you to review the [contributor guidelines](https://github.com/ToolJet/ToolJet/blob/develop/CONTRIBUTING.md) and ensure that you raise pull requests (PRs) for the issues assigned specifically to you. Since there's already an issue assigned to you, I encourage you to explore up-for-grabs labeled issues, and please comment on your interest in assigning. Thank you for your understanding, and I look forward to your continued involvement in the project.

Can you assign it to me ?

**Comment by tejakummarikuntla** [comment] 2023-08-28 18:48
Hey @subhajit20 , as there's already an issue assigned to you, let's wait to welcome other first-time contributors like yourself to the project.

**Comment by Sranjan0208** [comment] 2023-08-29 12:09
Can I work on this issue?

**Comment by yehoki** [comment] 2023-08-29 20:34
Hi, is it possible to be assigned to this issue please?

**Comment by sarfarazstark** [comment] 2023-08-30 11:49
If the issue is still open I would like to work on it

**Comment by tejakummarikuntla** [comment] 2023-09-04 17:28
Hey @Sranjan0208 , thanks for your interest, assigned the issue to you.

**Closed** 2023-09-20 09:40 UTC
Labels: good first issue, up-for-grabs, platform
