### ISSUE TITLE
[Query Manager]: filter search not working on backspace

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#3306] opened 2022-06-17 09:16 UTC
### Version Information
Latest
### Environment
All

### What is the expected behaviour?
Should filter on backspace

### What is the current behaviour?
Doesn't filter on backspace

### How to reproduce the issue?

1. Click on search icon on query manager
2. Search for a non-matching text
3. Press backspace and search for a matching text

### Screenshots or Screencast
https://user-images.githubusercontent.com/12490590/174268073-226c9fbb-0a80-4657-a3f6-9dd727e0d86d.mov

**Comment by TheLearneer** [comment] 2022-06-22 02:45
Hi there,

If it's up for grabs, I can give it a shot.

**Comment by withshubh** [comment] 2022-06-23 14:07
@TheLearneer 
Assigned it to you.

**Comment by TheLearneer** [comment] 2022-06-23 14:20
Hello there. 👋 
I basically wanted to discuss the problem and the possible solutions for the problem.

The problem is exactly in this line here
https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/Editor/Editor.jsx#L931-L937

**The problem**:
Basically when a search is done, all the values in the state `dataQueries` is changed with the filtered Queries.
For e.g. if initially the state has items [`tooljet`, `github`] and I search for `tooljet`, then the state will be replaced with just [`tooljet`]

**Solution**:
The ideal solution I can think up of is storing all the state values (upon making the API call) to a new state named something like `allDataQueries` or something similar.
And upon filtering we just save the filtered data in `dataQueries`.
We don't update the `allDataQueries` state asides from when fetching all the data through API call.
And regarding showing the queries, we use the existing `dataQueries` state as it is.

__NOTE:__ I already have a working version of the solution I have proposed in my local machine.
If it sounds good, I can move ahead with the approach.

_I would really appreciate any feedbacks and your thoughts._

@gondar00 @withshubh

**Comment by gondar00** [comment] 2022-06-24 07:47
Hi @TheLearneer, your solution sounds good. Please go ahead with your approach 👍🏻

**Closed** 2022-08-16 11:00 UTC
Labels: bug, good first issue, frontend, up-for-grabs
