### ISSUE TITLE
Audit Log - 'Search' button should be enabled with only a few filter options 

### ISSUE THREAD

**Issue by Gabuzomeuh67** [ToolJet/ToolJet#5295] opened 2023-01-11 12:40 UTC
in order to filter lines in the Audit Log lst, all filter options have to be filled : user, apps, resources, actions and dates

it would be useful to filter on a combination of only a few of them or even only one

**Comment by Nandinisaha13** [comment] 2023-01-12 17:11
Hey @Gabuzomeuh67 , I tried to replicate this but I can see it working on my side, can you be more specific case I should look for?

**Comment by Gabuzomeuh67** [comment] 2023-01-13 07:48
![screenshot](https://user-images.githubusercontent.com/122452789/212266055-6b1df8f8-aa12-4677-8ab0-86565d3fe523.png)

Hi here is a screenshot : I have select an app ('Untitled app') but the search button is still disabled

**Comment by Nandinisaha13** [comment] 2023-01-16 05:15
Hey @Gabuzomeuh67 I was able to search for an "unititled app". Can you please share which version are you on? I am in v2.0.0-ee1.5.4-cloud1.1.3.

**Comment by Gabuzomeuh67** [comment] 2023-01-16 14:58
Hi @Nandinisaha13 , we are running v1.31.1-ee1.5.4

**Comment by withshubh** [comment] 2023-01-17 09:48
Hey @Gabuzomeuh67 - The issue is fixed in the latest version i.e. ToolJet 2.0

Please use the latest version.
Closing this issue - feel free join [Community Slack](https://tooljet.com/slack) if you have any questions.

**Closed** 2023-01-17 09:48 UTC
Labels: feature request
