### ISSUE TITLE
documentation link looping

### ISSUE THREAD

**Issue by febinsathar** [ToolJet/ToolJet#852] opened 2021-09-27 18:40 UTC
when we click any documentation link eg: https://docs.tooljet.io/docs/widgets/number-input
this is triggering on a infinite loop of adding /doc to path and the page is getting stuck

**Comment by kpnigalye** [comment] 2021-09-30 04:51
I can check this out. Can you assign this to me?

**Comment by Navaneeth-pk** [comment] 2021-09-30 04:53
Sure, thanks for contributing :) 
@kpnigalye

**Comment by kpnigalye** [comment] 2021-10-03 04:02
Can you please tell me about the steps to follow to run this project in my local?

**Comment by Navaneeth-pk** [comment] 2021-10-03 06:08
We use Docusaurus for documentation and the files are located in the `docs` directory. To set up serving docs locally, please run `npm install` from within the `docs` directory and then run `npm start`. 

@kpnigalye

**Comment by kpnigalye** [comment] 2021-10-03 10:50
I observed this issue in the deployed app. When I am trying `http://localhost:3000/docs/widgets/number-input` link in my local, it shows me `Page not Found` error. So I am assuming this is related to broken links. 

docusaurus.donfig.js has following properties.
 ```
"onBrokenLinks": "ignore",
"onBrokenMarkdownLinks": "warn",
```
By default, `onBrokenLinks` is set to warn, but we have set it to `ignore`. May be that is causing this issue. Since the broken links detection is only available for a production build, we need to change it and see if that is causing the issue. Let me know your thoughts.

![image](https://user-images.githubusercontent.com/8084464/135747402-244e9050-6da6-42f9-8c08-cdf0fceabad7.png)

**Comment by Navaneeth-pk** [comment] 2021-10-04 02:34
I think `onBrokenLinks` is used during the build to detect broken links, it doesn't have any impact once the app is built.
https://github.com/facebook/docusaurus/issues/3136#issuecomment-664941437

404 page is being displayed correctly for you, maybe the issue is with the firebase config? you can try it by running `firebase serve` locally. 
@kpnigalye

**Comment by akshitarora921** [comment] 2021-10-06 10:10
@Navaneeth-pk it is replicating in firebase serve.
![image](https://user-images.githubusercontent.com/11087313/136183646-1f678ee3-a216-4d75-9612-1d71a151d9a2.png)

**Comment by kpnigalye** [comment] 2021-10-07 14:50
I am not sure how to run firebase locally. Can you please guide me? @akshitarora921

**Comment by Navaneeth-pk** [comment] 2021-10-15 02:16
Sorry, missed the notification. Assigned now.
@akshitarora921

**Comment by akshitarora921** [comment] 2021-10-15 11:15
@Navaneeth-pk As it is working fine through `npm start` so it is a firebase issue. Which means we need to make changes in `firebase.json` file?

**Comment by chtnnh** [comment] 2021-10-29 18:41
@Navaneeth-pk I want to get contributing to Tooljet and would like to start here! Could you assign this to me? I have cloned the repo and read the contribution guidelines.

**Comment by withshubh** [comment] 2022-04-07 04:45
Closing this issue as this is fixed.

**Closed by withshubh** 2022-04-07 04:45 UTC
Labels: bug, documentation, good first issue, hacktoberfest
