### ISSUE TITLE
Tooltip to be shown only for truncated text

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#10453] opened 2024-07-25 07:48 UTC
If a text is not truncated there's no need to show a tooltip on hover displaying the same value. 

https://github.com/user-attachments/assets/74959d6d-d7dc-4906-88b3-091c55ff85c2

**Comment by CuriousCoder00** [comment] 2024-07-25 11:04
I would like to work on it... I've found where this issue lies and what would be it's possible solution.
Now, should i wait for label `up-for-grabs` to be added then start working on it? or someone assign it to me?

**Comment by karan-rathod-316** [comment] 2024-07-25 11:36
Hi @CuriousCoder00,

Assigning this issue to you. Happy coding:-).

**Comment by CuriousCoder00** [comment] 2024-07-25 16:01
Added the PR.. if need changes do tell me. Thank you..

**Comment by PriteshKiri** [comment] 2024-07-25 16:29
Thanks for your contribution @CuriousCoder00. Moving the issue to review.

**Comment by PriteshKiri** [comment] 2024-08-13 14:52
This issue is open for community contribution. Feel free to ask for the assignments.

**Comment by CVamsi27** [comment] 2024-08-14 19:15
Hey @PriteshKiri, I would like to work on this.

**Comment by CuriousCoder00** [comment] 2024-08-14 19:34
Hey @PriteshKiri, I wanted to oplogize for the delay in submitting the PR and making necessary changes for the issue i was assigned. Unfortunately, I got caught up in some uni carriculm activies, which took more time than expected.
I understand that issue has been unassigned due to my delay, but I have completed the work and am ready to submit the new PR. I truly value the opportunity to contribute to this project and would love to help in any way I can.
Please let me know if I can proceed with the PR!!!

**Comment by PriteshKiri** [comment] 2024-08-18 07:13
Thanks so much for the PR, @CVamsi27! 

Just a quick note for next time—please wait for the issue to be assigned before you start working on it. This helps us keep everything organized and ensures that we're tracking issues effectively. Thanks again for your contribution! 🙌

**Comment by PriteshKiri** [comment] 2024-08-18 07:15
Hey @CuriousCoder00 , no worries at all—we completely understand! We appreciate your dedication to the project.

For now, the issue has been reassigned to another contributor, but we’d love to see you continue contributing. Feel free to pick up any issue under the `community contribution` label whenever you're ready. 

Your contributions are always valued!

**Comment by CVamsi27** [comment] 2024-08-18 12:25
> Thanks so much for the PR, @CVamsi27!
> 
> Just a quick note for next time—please wait for the issue to be assigned before you start working on it. This helps us keep everything organized and ensures that we're tracking issues effectively. Thanks again for your contribution! 🙌

Hey @PriteshKiri , sorry for that. I was trying to reproduce/fix the issue before asking for assigning. So, as soon as I figured out the solution, I quoted to work on this issue and push a PR.

**Closed** 2024-12-12 07:02 UTC
Labels: bug, up-for-grabs, roadmap, platform, community contribution
