### ISSUE TITLE
[Docker] Failed building server

### ISSUE THREAD

**Issue by deathemperor** [ToolJet/ToolJet#197] opened 2021-06-08 06:35 UTC
Machine: Apple M1, MacOS 11.4

I think it has something to do with M1, no?

<details> 
<summary>failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c gem install bundler && RAILS_ENV=production bundle install --jobs 20 --retry 5]: exit code: 137</summary>
docker compose up -d
[+] Building 180.9s (21/27)
 => [tooljet:development internal] load build definition from server.Dockerfile                                                                                        0.1s
 => => transferring dockerfile: 321B                                                                                                                                   0.0s
 => [tooljet-client:development internal] load build definition from client.Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 500B                                                                                                                                   0.0s
 => [tooljet-server:development internal] load build definition from server.Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 321B                                                                                                                                   0.0s
 => [tooljet:development internal] load .dockerignore                                                                                                                  0.0s
 => => transferring context: 89B                                                                                                                                       0.0s
 => [tooljet-client:development internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 66B                                                                                                                                       0.0s
 => [tooljet-server:development internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 89B                                                                                                                                       0.0s
 => [tooljet:development internal] load metadata for docker.io/library/ruby:2.7.3-buster                                                                               4.5s
 => [tooljet-client:development internal] load metadata for docker.io/library/node:14.17.0-alpine                                                                      4.3s
 => [tooljet-client:development 1/6] FROM docker.io/library/node:14.17.0-alpine@sha256:f07ead757c93bc5e9e79978075217851d45a5d8e5c48eaf823e7f12d9bbc1d3c               10.6s
 => => resolve docker.io/library/node:14.17.0-alpine@sha256:f07ead757c93bc5e9e79978075217851d45a5d8e5c48eaf823e7f12d9bbc1d3c                                           0.0s
 => => sha256:645fc0c6c96611d16cbb3252bf5edccea9124221e16f1407cf483f944e2716ed 6.73kB / 6.73kB                                                                         0.0s
 => => sha256:69982ba3cc3a84e32a718955abee7b677760fecbbf6c71d883a8392ab552164f 36.26MB / 36.26MB                                                                       6.6s
 => => sha256:23b960c2560ae1e047a378e94eb41e521c52c1c22860d196f5aaef1a297d74dd 2.30MB / 2.30MB                                                                         0.9s
 => => sha256:2f24eee88333ef6e2bd82a975c7b6dbc8460012bbfb021bc8ddf70d02cb9e88b 281B / 281B                                                                             1.1s
 => => sha256:f07ead757c93bc5e9e79978075217851d45a5d8e5c48eaf823e7f12d9bbc1d3c 1.43kB / 1.43kB                                                                         0.0s
 => => sha256:54ce125ebbced038b4b54b4c25ab1cb5c79fba1d0e153b23d35c0fc7f0a69101 1.16kB / 1.16kB                                                                         0.0s
 => => extracting sha256:69982ba3cc3a84e32a718955abee7b677760fecbbf6c71d883a8392ab552164f                                                                              2.5s
 => => extracting sha256:23b960c2560ae1e047a378e94eb41e521c52c1c22860d196f5aaef1a297d74dd                                                                              0.3s
 => => extracting sha256:2f24eee88333ef6e2bd82a975c7b6dbc8460012bbfb021bc8ddf70d02cb9e88b                                                                              0.0s
 => [tooljet-client:development internal] load build context                                                                                                           0.9s
 => => transferring context: 1.62MB                                                                                                                                    0.8s
 => [tooljet:development 1/7] FROM docker.io/library/ruby:2.7.3-buster@sha256:c4cea7e31130d2a5db09dc65eb8884d79f215cf7f49c01723d488a0c7be1e965                        48.1s
 => => resolve docker.io/library/ruby:2.7.3-buster@sha256:c4cea7e31130d2a5db09dc65eb8884d79f215cf7f49c01723d488a0c7be1e965                                             0.0s
 => => sha256:c4cea7e31130d2a5db09dc65eb8884d79f215cf7f49c01723d488a0c7be1e965 1.86kB / 1.86kB                                                                         0.0s
 => => sha256:477b92bf81002bbd0776e8e7eec4e6cecfd0d2ab89da4de56cb3b1c8059c9f08 7.24kB / 7.24kB                                                                         0.0s
 => => sha256:10697b0920c2b5c0b8c4facb21d455f8f62c442e507770d379d88189e0ec6ca5 2.00kB / 2.00kB                                                                         0.0s
 => => sha256:c54d9402d498e45ed396b5b6fe836f55e4ccadbad745decda3e9f83d880bc677 49.23MB / 49.23MB                                                                      24.8s
 => => sha256:6a8aff564b222789ed2823b88e0f1a69ac00cbcbf9349acb8a363d5ef9724182 7.69MB / 7.69MB                                                                         3.9s
 => => sha256:67e893e0778bb86166fb6799aec4e4ac337c4f10172386c8ae9cf3c787331d7d 9.98MB / 9.98MB                                                                         6.7s
 => => sha256:72bf2dd6193dae84aecaec1d65081288ca49fe0843460035cc060b5aa4e7a9a7 52.17MB / 52.17MB                                                                      15.7s
 => => sha256:71f77eac104c01f7e87f5cbb811de11a5838bf6dee161668583b6781499252bc 183.90MB / 183.90MB                                                                    42.3s
 => => sha256:9a79dd4ab4364b5a5c44fcf3b500901fe58adad2d95a258874a2ee72accd3bde 199B / 199B                                                                            17.1s
 => => sha256:834b4bb599b494e48630c2c9100bbc7c1114546c80cfec01d6d13c99fceeacad 22.76MB / 22.76MB                                                                      23.4s
 => => sha256:6bf51e6df4901e08959d2489853fbe33911925ffaeffc3470dd0df7a13031c56 176B / 176B                                                                            24.9s
 => => extracting sha256:c54d9402d498e45ed396b5b6fe836f55e4ccadbad745decda3e9f83d880bc677                                                                              1.7s
 => => extracting sha256:6a8aff564b222789ed2823b88e0f1a69ac00cbcbf9349acb8a363d5ef9724182                                                                              0.2s
 => => extracting sha256:67e893e0778bb86166fb6799aec4e4ac337c4f10172386c8ae9cf3c787331d7d                                                                              0.3s
 => => extracting sha256:72bf2dd6193dae84aecaec1d65081288ca49fe0843460035cc060b5aa4e7a9a7                                                                              2.0s
 => => extracting sha256:71f77eac104c01f7e87f5cbb811de11a5838bf6dee161668583b6781499252bc                                                                              4.8s
 => => extracting sha256:9a79dd4ab4364b5a5c44fcf3b500901fe58adad2d95a258874a2ee72accd3bde                                                                              0.0s
 => => extracting sha256:834b4bb599b494e48630c2c9100bbc7c1114546c80cfec01d6d13c99fceeacad                                                                              0.4s
 => => extracting sha256:6bf51e6df4901e08959d2489853fbe33911925ffaeffc3470dd0df7a13031c56                                                                              0.0s
 => [tooljet-server:development internal] load build context                                                                                                          12.8s
 => => transferring context: 161.17MB                                                                                                                                 12.7s
 => [tooljet:development internal] load build context                                                                                                                 12.2s
 => => transferring context: 161.17MB                                                                                                                                 12.1s
 => [tooljet-client:development 2/6] WORKDIR /app                                                                                                                      0.1s
 => [tooljet-client:development 3/6] COPY package.json package-lock.json  ./                                                                                           0.0s
 => CANCELED [tooljet-client:development 4/6] RUN npm install                                                                                                        165.4s
 => [tooljet-server:development 2/7] RUN apt update && apt install -y   build-essential    postgresql                                                                 16.2s
 => [tooljet-server:development 3/7] RUN mkdir -p /app                                                                                                                 0.2s
 => [tooljet:development 4/7] WORKDIR /app                                                                                                                             0.0s
 => [tooljet:development 5/7] COPY Gemfile Gemfile.lock ./                                                                                                             0.0s
 => ERROR [tooljet:development 6/7] RUN gem install bundler && RAILS_ENV=production bundle install --jobs 20 --retry 5                                               109.0s
------
 > [tooljet:development 6/7] RUN gem install bundler && RAILS_ENV=production bundle install --jobs 20 --retry 5:
#26 0.923 Successfully installed bundler-2.2.19
#26 0.923 1 gem installed
#26 1.104 The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
#26 2.370 Fetching gem metadata from https://rubygems.org/.........
#26 8.733 Fetching rake 13.0.3
#26 8.882 Installing rake 13.0.3
#26 8.923 Fetching concurrent-ruby 1.1.8
#26 8.924 Fetching minitest 5.14.4
#26 8.929 Fetching zeitwerk 2.4.2
#26 8.929 Fetching builder 3.2.4
#26 8.929 Fetching mini_portile2 2.5.1
#26 8.929 Fetching racc 1.5.2
#26 8.929 Fetching crass 1.0.6
#26 8.929 Fetching rack 2.2.3
#26 8.929 Fetching mini_mime 1.0.3
#26 8.929 Fetching public_suffix 4.0.6
#26 8.929 Fetching ast 2.4.2
#26 8.929 Fetching aws-eventstream 1.1.1
#26 8.929 Fetching nio4r 2.5.7
#26 8.929 Fetching websocket-extensions 0.1.5
#26 8.931 Fetching aws-partitions 1.455.0
#26 8.931 Fetching erubi 1.10.0
#26 8.931 Fetching marcel 1.0.0
#26 8.933 Fetching jmespath 1.4.0
#26 8.933 Fetching aws-sigv2 1.0.2
#26 9.049 Installing aws-sigv2 1.0.2
#26 9.051 Installing crass 1.0.6
#26 9.067 Installing aws-eventstream 1.1.1
#26 9.070 Installing mini_mime 1.0.3
#26 9.072 Installing erubi 1.10.0
#26 9.081 Fetching bcrypt 3.1.16
#26 9.109 Installing mini_portile2 2.5.1
#26 9.112 Installing jmespath 1.4.0
#26 9.118 Installing aws-partitions 1.455.0
#26 9.146 Fetching msgpack 1.4.2
#26 9.177 Fetching bson 4.12.0
#26 9.181 Installing nio4r 2.5.7 with native extensions
#26 9.195 Using bundler 2.1.4
#26 9.195 Fetching byebug 11.1.3
#26 9.218 Installing minitest 5.14.4
#26 9.245 Fetching dotenv 2.7.6
#26 9.262 Fetching method_source 1.0.0
#26 9.267 Installing rack 2.2.3
#26 9.270 Fetching thor 1.1.0
#26 9.327 Installing concurrent-ruby 1.1.8
#26 9.333 Installing bcrypt 3.1.16 with native extensions
#26 9.344 Fetching multi_json 1.15.0
#26 9.403 Installing msgpack 1.4.2 with native extensions
#26 9.412 Installing dotenv 2.7.6
#26 9.415 Installing method_source 1.0.0
#26 9.476 Installing byebug 11.1.3 with native extensions
#26 9.493 Installing bson 4.12.0 with native extensions
#26 9.508 Installing multi_json 1.15.0
#26 9.521 Installing thor 1.1.0
#26 10.07 Fetching faraday-net_http 1.0.1
#26 10.07 Fetching multipart-post 2.1.1
#26 10.08 Fetching ruby2_keywords 0.0.4
#26 10.19 Installing faraday-net_http 1.0.1
#26 10.20 Installing ruby2_keywords 0.0.4
#26 10.21 Installing multipart-post 2.1.1
#26 11.62 Fetching google-protobuf 3.15.8
#26 11.62 Fetching ffi 1.15.0
#26 11.83 Installing google-protobuf 3.15.8 with native extensions
#26 12.00 Installing ffi 1.15.0 with native extensions
#26 14.05 Installing websocket-extensions 0.1.5
#26 14.06 Installing ast 2.4.2
#26 14.07 Installing marcel 1.0.0
#26 14.09 Installing builder 3.2.4
#26 14.09 Installing zeitwerk 2.4.2
#26 14.14 Installing public_suffix 4.0.6
#26 14.27 Installing racc 1.5.2 with native extensions
#26 15.92 Fetching memoist 0.16.2
#26 15.93 Fetching jwt 2.2.2
#26 15.93 Fetching google-cloud-errors 1.1.0
#26 15.93 Fetching os 1.1.1
#26 15.93 Fetching mime-types-data 3.2021.0225
#26 15.94 Fetching rbtree 0.4.4
#26 15.94 Fetching multi_xml 0.6.0
#26 15.94 Fetching regexp_parser 2.1.1
#26 16.09 Installing jwt 2.2.2
#26 16.10 Installing os 1.1.1
#26 16.11 Installing memoist 0.16.2
#26 16.12 Installing google-cloud-errors 1.1.0
#26 16.13 Installing regexp_parser 2.1.1
#26 16.18 Installing multi_xml 0.6.0
#26 16.36 Installing rbtree 0.4.4 with native extensions
#26 16.42 Installing mime-types-data 3.2021.0225
#26 20.28 Fetching kaminari-core 1.2.1
#26 20.29 Fetching lockbox 0.6.4
#26 20.29 Fetching mysql2 0.5.3
#26 20.29 Fetching rb-fsevent 0.10.4
#26 20.29 Fetching parallel 1.20.1
#26 20.30 Fetching pg 1.2.3
#26 20.31 Fetching rainbow 3.0.0
#26 20.42 Installing parallel 1.20.1
#26 20.43 Installing kaminari-core 1.2.1
#26 20.46 Installing rainbow 3.0.0
#26 20.49 Installing rb-fsevent 0.10.4
#26 20.50 Installing mysql2 0.5.3 with native extensions
#26 20.54 Installing pg 1.2.3 with native extensions
#26 20.57 Installing lockbox 0.6.4
#26 20.84 Fetching redis 4.2.5
#26 20.99 Installing redis 4.2.5
#26 24.42 Fetching ruby-progressbar 1.11.0
#26 24.42 Fetching rexml 3.2.5
#26 24.43 Fetching unicode-display_width 2.0.0
#26 24.43 Fetching spring 2.1.1
#26 24.43 Fetching simple_command 0.1.0
#26 24.53 Installing unicode-display_width 2.0.0
#26 24.56 Installing spring 2.1.1
#26 24.56 Installing simple_command 0.1.0
#26 24.56 Installing ruby-progressbar 1.11.0
#26 24.62 Installing rexml 3.2.5
#26 25.63 Fetching aws-sigv4 1.2.3
#26 25.63 Fetching mail 2.7.1
#26 25.63 Fetching elasticsearch-api 7.12.0
#26 25.64 Fetching rack-test 1.1.0
#26 25.78 Installing aws-sigv4 1.2.3
#26 25.81 Installing rack-test 1.1.0
#26 25.87 Installing elasticsearch-api 7.12.0
#26 25.92 Installing mail 2.7.1
#26 28.93 Fetching request_store 1.5.0
#26 28.94 Fetching i18n 1.8.10
#26 28.94 Fetching rack-cors 1.1.1
#26 28.94 Fetching tzinfo 2.0.4
#26 28.94 Fetching sprockets 4.0.2
#26 29.07 Installing rack-cors 1.1.1
#26 29.08 Installing request_store 1.5.0
#26 29.08 Installing i18n 1.8.10
#26 29.12 Installing tzinfo 2.0.4
#26 29.13 Installing sprockets 4.0.2
#26 34.50 Fetching websocket-driver 0.7.3
#26 34.50 Fetching puma 5.3.1
#26 34.51 Fetching parser 3.0.1.1
#26 34.51 Fetching faraday 1.3.0
#26 34.52 Fetching bootsnap 1.7.3
#26 34.52 Fetching addressable 2.7.0
#26 34.53 Fetching mongo 2.14.0
#26 34.53 Fetching googleapis-common-protos-types 1.0.6
#26 34.54 Fetching mime-types 3.3.1
#26 34.55 Fetching nokogiri 1.11.5
#26 34.56 Fetching ethon 0.14.0
#26 34.57 Fetching rb-inotify 0.10.1
#26 34.58 Fetching aws-sdk-core 3.114.0
#26 34.58 Fetching activesupport 6.1.3.1
#26 34.65 Installing websocket-driver 0.7.3 with native extensions
#26 34.79 Installing googleapis-common-protos-types 1.0.6
#26 34.82 Installing bootsnap 1.7.3 with native extensions
#26 34.82 Installing addressable 2.7.0
#26 34.83 Installing rb-inotify 0.10.1
#26 34.84 Installing mime-types 3.3.1
#26 34.85 Installing ethon 0.14.0
#26 34.87 Installing puma 5.3.1 with native extensions
#26 35.09 Installing faraday 1.3.0
#26 35.16 Fetching listen 3.5.1
#26 35.20 Installing activesupport 6.1.3.1
#26 35.64 Installing aws-sdk-core 3.114.0
#26 35.68 Installing listen 3.5.1
#26 35.78 Fetching grpc 1.37.0
#26 35.79 Fetching httparty 0.18.1
#26 35.82 Installing parser 3.0.1.1
#26 35.86 Fetching typhoeus 1.4.0
#26 35.98 Installing httparty 0.18.1
#26 36.03 Installing mongo 2.14.0
#26 36.09 Installing typhoeus 1.4.0
#26 37.01 Installing nokogiri 1.11.5 with native extensions
#26 37.66 Installing grpc 1.37.0 with native extensions
#26 38.07 Fetching elasticsearch-transport 7.12.0
#26 38.07 Fetching google-cloud-env 1.5.0
#26 38.07 Fetching signet 0.15.0
#26 38.07 Fetching aws-sdk-accessanalyzer 1.19.0
#26 38.07 Fetching aws-sdk-acm 1.41.0
#26 38.07 Fetching aws-sdk-alexaforbusiness 1.47.0
#26 38.07 Fetching aws-sdk-acmpca 1.35.0
#26 38.08 Fetching aws-sdk-amplifybackend 1.3.0
#26 38.08 Fetching aws-sdk-amplify 1.29.0
#26 38.08 Fetching aws-sdk-apigatewaymanagementapi 1.21.0
#26 38.08 Fetching aws-sdk-apigatewayv2 1.32.0
#26 38.08 Fetching aws-sdk-apigateway 1.62.0
#26 38.08 Fetching aws-sdk-appconfig 1.14.0
#26 38.08 Fetching aws-sdk-applicationdiscoveryservice 1.35.0
#26 38.08 Fetching aws-sdk-appflow 1.10.0
#26 38.09 Fetching aws-sdk-appintegrationsservice 1.2.0
#26 38.09 Fetching aws-sdk-applicationautoscaling 1.51.0
#26 38.19 Installing google-cloud-env 1.5.0
#26 38.22 Installing aws-sdk-amplifybackend 1.3.0
#26 38.25 Installing aws-sdk-apigatewaymanagementapi 1.21.0
#26 38.28 Installing aws-sdk-applicationdiscoveryservice 1.35.0
#26 38.28 Installing aws-sdk-amplify 1.29.0
#26 38.29 Installing aws-sdk-accessanalyzer 1.19.0
#26 38.29 Installing elasticsearch-transport 7.12.0
#26 38.30 Installing aws-sdk-alexaforbusiness 1.47.0
#26 38.31 Installing aws-sdk-applicationautoscaling 1.51.0
#26 38.32 Installing signet 0.15.0
#26 38.34 Installing aws-sdk-appflow 1.10.0
#26 38.35 Installing aws-sdk-acm 1.41.0
#26 38.35 Installing aws-sdk-apigateway 1.62.0
#26 38.41 Installing aws-sdk-apigatewayv2 1.32.0
#26 39.05 Installing aws-sdk-acmpca 1.35.0
#26 39.09 Installing aws-sdk-appconfig 1.14.0
#26 43.23 Installing aws-sdk-appintegrationsservice 1.2.0
#26 80.08 Fetching aws-sdk-appmesh 1.35.0
#26 80.08 Fetching aws-sdk-appstream 1.52.0
#26 80.08 Fetching aws-sdk-applicationinsights 1.18.0
#26 80.09 Fetching aws-sdk-appsync 1.40.0
#26 80.09 Fetching aws-sdk-appregistry 1.5.0
#26 80.09 Fetching aws-sdk-auditmanager 1.7.0
#26 80.09 Fetching aws-sdk-athena 1.37.0
#26 80.10 Fetching aws-sdk-augmentedairuntime 1.12.0
#26 80.11 Fetching aws-sdk-autoscaling 1.60.0
#26 80.11 Fetching aws-sdk-batch 1.47.0
#26 80.12 Fetching aws-sdk-autoscalingplans 1.31.0
#26 80.12 Fetching aws-sdk-braket 1.7.0
#26 80.12 Fetching aws-sdk-backup 1.28.0
#26 80.12 Fetching aws-sdk-budgets 1.38.0
#26 86.48 Installing aws-sdk-budgets 1.38.0
#26 86.49 Installing aws-sdk-braket 1.7.0
#26 86.51 Installing aws-sdk-auditmanager 1.7.0
#26 86.51 Installing aws-sdk-backup 1.28.0
#26 86.52 Installing aws-sdk-autoscalingplans 1.31.0
#26 86.52 Installing aws-sdk-appregistry 1.5.0
#26 86.54 Installing aws-sdk-augmentedairuntime 1.12.0
#26 86.54 Installing aws-sdk-athena 1.37.0
#26 86.54 Installing aws-sdk-appstream 1.52.0
#26 86.56 Installing aws-sdk-batch 1.47.0
#26 86.56 Installing aws-sdk-applicationinsights 1.18.0
#26 86.58 Installing aws-sdk-appsync 1.40.0
#26 86.58 Installing aws-sdk-appmesh 1.35.0
#26 86.77 Installing aws-sdk-autoscaling 1.60.0
#26 108.7 Killed
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c gem install bundler && RAILS_ENV=production bundle install --jobs 20 --retry 5]: exit code: 137
</details>

**Comment by deathemperor** [comment] 2021-06-08 06:44
I'm able to install it on an Ubuntu so I guess it's really a M1 specific issue

**Comment by Navaneeth-pk** [comment] 2021-06-08 07:05
I think the same, the issue is specific to M1.

There is a related issue https://github.com/ToolJet/ToolJet/issues/151

**Comment by Navaneeth-pk** [comment] 2021-09-15 16:06
Closing this issue since we migrated from Rails to Node.js.

**Closed by Navaneeth-pk** 2021-09-15 16:06 UTC
Labels: bug
