### ISSUE TITLE
Enhancement: Enable "Send" Button Execution on Hitting Enter/Return Key

### ISSUE THREAD

**Issue by tejakummarikuntla** [ToolJet/ToolJet#6947] opened 2023-07-06 17:11 UTC
### Overview
In the "Suggest Datasource" section of the Global Datasource modal, currently, the "send" button requires a mouse click to execute. It would be beneficial to enhance the user experience by enabling the execution of the "send" button action when the Enter/Return key is pressed from the keyboard.

### Steps to find out and try:

1. Open the Global Datasource modal.
2. Navigate to the "Suggest Datasource" section by clicking on `suggest' In "Don't see what you were looking for?
Suggest".
3. Type the necessary information in the input fields.
4. The button "send" should be executed on hitting enter/return key from the keyboard.

### Expected Behavior:
Upon pressing the Enter/Return key, the "send" button should be executed.

### Screenshot
![image](https://github.com/ToolJet/ToolJet/assets/34749692/4beeb381-16e9-467c-b4fd-e992d0c7d865)

**Comment by shyamtawli** [comment] 2023-07-06 18:10
Hey, I would like to try my hands on it. Please assign.

**Comment by tejakummarikuntla** [comment] 2023-07-06 18:26
Hey @shyamtawli , thank you for your interest, assigned this to you.

**Comment by shyamtawli** [comment] 2023-07-09 14:22
Hey @manavkush I appreciate your work but the issue is assigned to me. I know I have taken too much time to open a PR. But I was facing some problems with my network so the cloning is failing. Now I can open a PR.

**Comment by manavkush** [comment] 2023-07-10 03:30
Hey @shyamtawli I saw that you're not working on it for 3 days and the issue was simple. I was able to do it for learning as it was a up-for-grabs tagged. Do try to finish it asap next time. 👍

**Closed** 2023-08-10 11:25 UTC
Labels: good first issue, up-for-grabs, status: tested
