### ISSUE TITLE
[Pagination Component] Fix casing with event name to Title case

### ISSUE THREAD

**Issue by DevangAgarwal93** [ToolJet/ToolJet#10946] opened 2024-10-11 05:26 UTC
In the name of events of components, we use sentence case - where only the first letter of the first word is **capitalized**. 
Need to keep it consistent for the **pagination component** event name as well.

Below is a comparison of pagination event name casing and table event name casing. 

The event name has the first letter of every word capitalized in the pagination component as seen below in the screenshot. The event name should be changed from "On Page Change" to "On page change"
![Image](https://github.com/user-attachments/assets/aeebf73f-07e4-4913-9c49-b2263f56e751)

For reference Events in the Table component where only the first letter of the first word is capitalized. (which is the same across events with other components as well). Need to make the pagination event name case the same as that of the table. 
![Image](https://github.com/user-attachments/assets/6d71bca0-4caa-4273-8ed7-41956df29bb1)

**Comment by KrishDave1** [comment] 2024-10-11 06:10
Can I work on this issue?Please assign it to me.

**Comment by PriteshKiri** [comment] 2024-10-11 06:22
@KrishDave1  assigned. Happy coding!   

Please note that the deadline for this task is 3 days from the day of the assignment. Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by KrishDave1** [comment] 2024-10-12 18:05
While setting up locally ,I am unable to run the project.I have messaged yesterday in slack as well.
This is the console of the page when running docker compose.Is there some issue on my end? @PriteshKiri 
![image](https://github.com/user-attachments/assets/55259f6a-39c0-46ed-878c-c7c0c17f30fe)

**Comment by FurquanAnwer** [comment] 2024-10-12 18:13
Did you run server? Check whether it is running successfully or not.

**Comment by Malay207** [comment] 2024-10-12 19:38
I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?

**Comment by PriteshKiri** [comment] 2024-10-13 11:52
Hey @Malay207 , this issue has already been assigned.  Please check out other open issues under the `community contribution`.

**Comment by chethanBy** [comment] 2024-10-13 12:41
i see that the issue is not solved yet. i would like to contribute. I have identified and tested the changes.

**Comment by PriteshKiri** [comment] 2024-10-14 06:10
Hey @KrishDave1 ,

Any updates on the issue? Please let me know if you are facing any problems.

**Comment by career-yashaswee** [comment] 2024-10-14 12:03
Would love to work on it. I have identified key code changes.

**Comment by karandevhub** [comment] 2024-10-15 05:15
I would like to contribute!. Could you please assign it to me?

**Comment by KrishDave1** [comment] 2024-10-15 05:47
> Hey @KrishDave1 ,
> 
> Any updates on the issue? Please let me know if you are facing any problems.

Yeah would take 1 more day for a PR

**Comment by mayurathavale18** [comment] 2024-10-18 06:46
I would like to work on this issue, Please assign this to me

**Comment by PriteshKiri** [comment] 2024-10-18 07:00
Hey @KrishDave1,

Any updates on the issue?

**Comment by PriteshKiri** [comment] 2024-10-18 07:04
Hey @mayurathavale18,

Thanks for your interest in contributing! 

If we don't hear back from @KrishDave1 soon, we'll assign the issue to you.

**Comment by mayurathavale18** [comment] 2024-10-18 07:06
Okay thank you

**Comment by MihirVargante** [comment] 2024-10-18 15:18
can i make PR for this?

**Comment by Chetan0000** [comment] 2024-10-20 17:38
Hey @PriteshKiri can i work on this issue...?

**Comment by PriteshKiri** [comment] 2024-10-21 05:40
@mayurathavale18 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment] 2024-10-21 05:43
Hey @MihirVargante @Chetan0000 , this issue has already been assigned.  Please check out other open issues under the `community contribution` label.

**Comment by PriteshKiri** [comment] 2024-10-25 12:26
Hey @mayurathavale18 

Any update on the issue? Please let me know if you are facing any issues.

**Comment by mayurathavale18** [comment] 2024-10-26 10:20
@PriteshKiri  Yes, will send the PR today.

**Comment by mayurathavale18** [comment] 2024-10-26 10:44
@PriteshKiri The PR has been raised.
Feature/10946 pagination component #11136

Please review and let me know.

**Comment by PriteshKiri** [comment] 2024-10-29 07:41
@mayurathavale18 unassigning the issue as the PR is closed.

**Comment by PriteshKiri** [comment] 2024-10-29 07:41
This issue is now open for the contribution 🙌

**Comment by mayurathavale18** [comment] 2024-10-29 08:17
> This issue is now open for the contribution 🙌 

Please give some clarity on the status of the issue Pagination Component Case change issue.

What does it mean by issue has been unassigned? 
Is the PR accepted? 
I already changed the casing and sent the PR, first PR was closed because it had that licence/CLA error. So the new PR with no licence/CLA has been raised.

So what exactly is the status?

**Comment by Chetan0000** [comment] 2024-10-29 08:18
Hey @PriteshKiri i would love to work on this issue,
Can you please assign it to me.

**Comment by PriteshKiri** [comment] 2024-10-30 08:25
Hey @mayurathavale18,

We appreciate your efforts! It looks like the issue was closed without comments, and we couldn’t find another PR linked to it, so the team decided to move forward with the issue.

For future contributions, please remember to add comments on PRs and link them to their respective issues to keep everything organized.

Feel free to request assignments on issues labeled `community contribution` for future contributions!

**Comment by PriteshKiri** [comment] 2024-10-30 08:26
@Chetan0000 assigned. Happy Hacktoberfest! 🎃  

Please make sure that,
 - You sign the CLA after submitting your PR. 
 - You complete this task in 3 days from the day of the assignment.   
 
Thank you for showing interest in contributing to ToolJet! Feel free to reach out to us in our [Slack community](https://join.slack.com/t/tooljet/shared_invite/zt-2rk4w42t0-ZV_KJcWU9VL1BBEjnSHLCA) if you have any questions.

**Comment by PriteshKiri** [comment] 2024-11-04 09:41
Hey @Chetan0000  ,
Thank you so much for your contribution! 🙌
Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Comment by PriteshKiri** [comment] 2024-11-19 10:47
Hey @Chetan0000,

Have added some comment on your PR, can you please check?

**Comment by Chetan0000** [comment] 2024-11-20 16:11
Hey @PriteshKiri 

I have raised a new PR with the necessary changes, can you please check.

**Comment by PriteshKiri** [comment] 2024-11-21 08:12
Thank you so much for your contribution! 🙌

Please keep an eye on your PR, as we may add some review comments if needed before merging it.

**Closed** 2024-11-22 06:18 UTC
Labels: bug, good first issue, roadmap, appbuilder, community contribution
