### ISSUE TITLE
Add border color property to button styles

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#4297] opened 2022-10-04 11:09 UTC
### Is your proposal related to a problem?

There's no option to set a border color to the button component. 

### Describe the solution you'd like

Add a border color property to the button component.

<img width="680" alt="Screenshot 2022-10-04 at 4 38 25 PM" src="https://user-images.githubusercontent.com/25361949/193804008-e2a71768-a06c-43a1-90e2-d5a72df38c45.png">

**Comment by Utkarsh212** [comment] 2022-10-04 11:10
Please assign this issue to me so that I can work on it

**Comment by Syed-Ansar** [comment] 2022-10-04 11:12
Hey @withshubh please assign it to me. I will work on this issue.

**Comment by withshubh** [comment] 2022-10-04 11:23
Hi @Syed-Ansar 👋  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by Syed-Ansar** [comment] 2022-10-04 11:37
> Hey @Syed-Ansar - There are issues that were already assigned to you. Please make a PR for them first. 😄

Hey @Syed-Ansar no one has assigned me the issue, this is my first one.

**Comment by prateek565** [comment] 2022-10-04 11:39
hi @withshubh  plz review my pr in this #4164

**Comment by TheLearneer** [comment] 2022-10-04 11:40
> No one has assigned me the issue, this is my first one.

@Syed-Ansar Please follow up this link to see all the active issues you are assigned to
https://github.com/ToolJet/ToolJet/issues/assigned/Syed-Ansar

**Comment by withshubh** [comment] 2022-10-04 11:41
> > Hey @Syed-Ansar - There are issues that were already assigned to you. Please make a PR for them first. 😄
> 
> Hey @Syed-Ansar no one has assigned me the issue, this is my first one.

Hey Syed,
I found these two issues assigned to you:
- https://github.com/ToolJet/ToolJet/issues/3295
- https://github.com/ToolJet/ToolJet/issues/2860

**Comment by withshubh** [comment] 2022-10-04 11:41
> > No one has assigned me the issue, this is my first one.
> 
> @Syed-Ansar Please follow up this link to see all the active issues you are assigned to [ToolJet/ToolJet/issues/assigned/Syed-Ansar](https://github.com/ToolJet/ToolJet/issues/assigned/Syed-Ansar)

Thanks @TheLearneer

**Comment by withshubh** [comment] 2022-10-04 11:43
> hi @withshubh plz review my pr in this #4164

Hey @prateek565 - please be patient we will review the PRs as soon as possible.

**Comment by Syed-Ansar** [comment] 2022-10-04 11:45
> > > Hey @Syed-Ansar - There are issues that were already assigned to you. Please make a PR for them first. 😄
> > 
> > 
> > Hey @Syed-Ansar no one has assigned me the issue, this is my first one.
> 
> Hey Syed, I found these two issues assigned to you:
> 
> * [Add on-hover highlighting for data sources list on query panel #3295](https://github.com/ToolJet/ToolJet/issues/3295)
> * [Disable home page scrolling #2860](https://github.com/ToolJet/ToolJet/issues/2860)

Oh yes, These were the issue of 3-4 months back 👍

**Comment by Syed-Ansar** [comment] 2022-10-04 11:48
> > > Hey @Syed-Ansar - There are issues that were already assigned to you. Please make a PR for them first. 😄
> > 
> > 
> > Hey @Syed-Ansar no one has assigned me the issue, this is my first one.
> 
> Hey Syed, I found these two issues assigned to you:
> 
> * [Add on-hover highlighting for data sources list on query panel #3295](https://github.com/ToolJet/ToolJet/issues/3295)
> * [Disable home page scrolling #2860](https://github.com/ToolJet/ToolJet/issues/2860)

I will work on this and take this one up.

**Comment by racky7** [comment] 2022-10-04 11:58
@withshubh I want to work on this. Please assign it to me.

**Comment by withshubh** [comment] 2022-10-04 12:07
Hi @racky7 👋  

Thanks for showing interest in contributing to ToolJet. We've assigned the issue to you. 

If you have any questions related to setting up ToolJet, feel free to join our Slack community here: [Slack community](https://tooljet.com/slack)

**Comment by racky7** [comment] 2022-10-04 12:27
@withshubh Thanks. Can you please tell me the directory (path of this component) of this issue?

**Comment by TheLearneer** [comment] 2022-10-04 12:30
@racky7 You will need to make changes in two of the files

First one would be: https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/Editor/Components/Button.jsx
Which would be responsible for showing the actual styles

Second one would be: https://github.com/ToolJet/ToolJet/blob/develop/frontend/src/Editor/WidgetManager/widgetConfig.js
Which would be responsible for showing the field in the editor for the user

**Comment by vedant-z** [comment] 2022-10-04 14:15
@withshubh I wanna give a try.

**Comment by Syed-Ansar** [comment] 2022-10-04 15:44
Hey @withshubh I had raised the PR and I was the first one to comment for this issue. Can you please assign it to me as racky has unassigned his assignment.

**Comment by AyushK-101** [comment] 2022-10-04 17:40
@withshubh @TheLearneer I have made a PR regarding this issue (#4304) , please review it

**Comment by arpitnath** [comment] 2022-10-04 22:32
@AyushK-101 All pull requests will be considered invalid if the issue is not assigned to you.

@withshubh Please assign to the first person who expressed interest. 
I do not have enough context of the above conversation 😅

**Comment by adityapathakk** [comment] 2022-10-05 03:14
Hi, it'd be great if I could up this issue!

**Comment by OjashKush** [comment] 2022-10-05 07:30
can you assigned this to me?

**Comment by WadekarPrashant** [comment] 2022-10-05 08:19
Hey, can I work on this issue? Please assign it to me.
@TheLearneer

**Comment by TheOjasSingh** [comment] 2022-10-05 08:31
can you assign this issue to me

**Comment by TheLearneer** [comment] 2022-10-05 09:13
> Hey, can I work on this issue? Please assign it to me. @TheLearneer

Hello, sorry but I am not a maintainer of this project.
I am just trying my best to help the maintainers during the hacktoberfest (there is lots of chaos during this time).

Maintainers will get back you as soon as they are free 🙇

**Comment by daniel-shuy** [comment] 2022-10-05 15:28
@arpitnath @withshubh I suggest you guys change it to first-PR-approved (no "ticket reservation"), like what [fluttercommunity/plus-plugins](https://github.com/fluttercommunity/plus_plugins/issues/1108#issuecomment-1263071221) did.

There are too many issue squatters that request to be assigned to an issue without first understand what it is, which prevents others from working on it, and adds to maintainer overhead.

**Comment by TheLearneer** [comment] 2022-10-05 15:32
@daniel-shuy That will only cause more chaos and more work on maintainers side, because everyone will start making PR. and then once a single PR is approved, maintainers will have to close all others while keeping track of which issue it was for and so on.

Basically it's too much work if that philosophy is implemented 🙏

**Comment by daniel-shuy** [comment] 2022-10-05 15:39
@TheLearneer it shouldn't be too difficult since the issue will show all PRs referencing it:
![image](https://user-images.githubusercontent.com/17351764/194102240-32f964c1-204a-426d-bf0b-bb22caaed495.png)

I was thinking it would reduce maintainer overhead, but if it increases maintainer overhead, then yeah its not a good idea. Maybe it depends on the average task difficulty as well.

**Comment by mayankagnihotri7** [comment] 2022-10-05 17:29
Hey, @withshubh can I take this up please? Can you please assign it to me?

**Comment by BajajAyush** [comment] 2022-10-05 19:13
Please assign it to me

**Comment by DevWig** [comment] 2022-10-05 19:40
I can take this issue if no one has picked it up yet @withshubh

**Comment by shashwat933** [comment] 2022-10-06 10:30
Hello @withshubh , please assign this issue to me

**Comment by Priyanshu-Singh-1** [comment] 2022-10-06 13:28
I want to take this issue @withshubh. Can you please assign me this issue..

**Comment by AyushK-101** [comment] 2022-10-06 16:52
> @AyushK-101 All pull requests will be considered invalid if the issue is not assigned to you.
> 
> @withshubh Please assign to the first person who expressed interest. I do not have enough context of the above conversation 😅

@arpitnath I didn't know about that, actually the user who was assigned this issue removed his assignment and now there are a bunch of people who wish to contribute to this issue, so I thought it would be best to make a PR directly. I get it , in case the issue stays unresolved, feel free to review my PR.

**Comment by withshubh** [comment] 2022-10-07 05:58
Hey @vedant-z 
Assigning the issue to you since you were the first to show interest after the previous assignee unassigned himself.

**Comment by vedant-z** [comment] 2022-10-07 06:06
@withshubh Thanks a lot

**Comment by withshubh** [comment] 2022-10-07 06:08
Hi all,

Thanks for showing interest in contributing to ToolJet but the issue is already assigned to someone. 

You can check out other open issues here: [hacktoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest).

cc: @Syed-Ansar @AyushK-101 @adityapathakk @OjashKush @WadekarPrashant @TheOjasSingh @mayankagnihotri7 @BajajAyush @shashwat933 @Priyanshu-Singh-1 @Avicenne-b

**Comment by prakhar-198** [comment] 2022-10-09 16:01
Is there something still left to be done? assign me.

**Closed** 2022-10-11 03:38 UTC
Labels: good first issue, feature request, hacktoberfest, up-for-grabs
