### ISSUE TITLE
Can't resolve '@tooljet/plugins/client'

### ISSUE THREAD

**Issue by NimoSayGoodBye** [ToolJet/ToolJet#3567] opened 2022-07-11 09:03 UTC
Module not found: Error: Can't resolve '@tooljet/plugins/client' in '/Users/nimo/Downloads/saas-toolJet-main/frontend/src/Editor/DataSourceManager/SourceComponents'
<img width="810" alt="截屏2022-07-11 下午5 02 35" src="https://user-images.githubusercontent.com/12082971/178228358-c27ef1c9-cac5-4b4d-bb93-66337ce69824.png">

How can I solve it?

**Comment by withshubh** [comment] 2022-07-31 11:53
Hey @NimoSayGoodBye 
Closing this issue as this is not a bug. If you still face any other issues in installing ToolJet then you can ask away in our [Slack Community](https://join.slack.com/t/tooljet/shared_invite/zt-r2neyfcw-KD1COL6t2kgVTlTtAV5rtg).

**Closed by withshubh** 2022-07-31 11:53 UTC
Labels: bug
