### ISSUE TITLE
Tabs in Modal: content below tab page still bound to tab page.

### ISSUE THREAD

**Issue by Robintago** [ToolJet/ToolJet#2323] opened 2022-02-22 13:14 UTC
### Environment

ToolJet Cloud

### What is the expected behaviour?

Content below a tab page in a modal should stay visible upon changing pages.

### What is the current behaviour?

Content below a tab page in a modal is bound to a single tab page.

### How to reproduce the issue?

1. Display a modal.
2. Add a tab-widget.
3. Place some content under the tab widget.
4. Change tab page.

### Screenshots or Screencast

<img width="733" alt="image" src="https://user-images.githubusercontent.com/94896750/155139487-bc0780ce-573c-4cd5-aa73-fe9ecd48ec88.png">

<img width="733" alt="image" src="https://user-images.githubusercontent.com/94896750/155139562-60e22b76-565e-4574-8012-3e0aa591af93.png">

**Comment by withshubh** [comment] 2022-07-31 22:55
@arpitnath - Please take a look at this issue

**Comment by withshubh** [comment] 2022-08-04 22:54
Closing - couldn't reproduce the issue.

**Closed by withshubh** 2022-08-04 22:54 UTC
Labels: bug, widget
