### ISSUE TITLE
Bugfix: Toast alert for making the application public

### ISSUE THREAD

**Issue by arpitnath** [ToolJet/ToolJet#1228] opened 2021-10-24 04:20 UTC
### What is the expected behaviour?
Toast alerts for making the application public should be on top of the modal.

### What is the current behaviour?
Toast alerts for making the application public are under the backdrop of the modal.

### How to reproduce the issue?
- Create an app
- Click on the share button 
- Toggle the button `Make application public ?`

### Screenshot
<img width="1680" alt="Screenshot 2021-10-24 at 9 48 25 AM" src="https://user-images.githubusercontent.com/67645175/138580561-a39ec8da-b5df-4ab6-a63f-394750829960.png">

### Reference 
issue: #759 
PR: #760

**Comment by arpitnath** [comment] 2021-10-30 03:27
@rahulbhatt1899 Are you still working on it?

**Comment by Ksathwik03** [comment] 2021-10-30 03:49
Since there is no reply from the assigne can i work on it @arpitnath

**Comment by Ksathwik03** [comment] 2021-10-30 11:13
....

**Comment by arpitnath** [comment] 2021-10-30 11:20
@Ksathwik03, let us wait till monday

**Comment by Ksathwik03** [comment] 2021-10-30 11:21
> @Ksathwik03, let us wait till monday

Sure 👍🏻

**Comment by karlrez** [comment] 2021-11-28 23:59
Hi, I would be interested in contributing, can you assign this to me? I've got this running on localhost and was able to reproduce this issue.

**Comment by Navaneeth-pk** [comment] 2021-11-29 07:27
Thanks for your interest in contributing to Tooljet. Assigned the issue to you.
@karlrez

**Closed** 2021-12-03 13:10 UTC
Labels: bug, frontend, hacktoberfest
