### ISSUE TITLE
Close folder creation input box when user clicks outside

### ISSUE THREAD

**Issue by sherfin94** [ToolJet/ToolJet#955] opened 2021-10-08 08:47 UTC
### Is your proposal related to a problem?

Presently, on the application listing screen, if a user clicks on `+ Folder`, the input field for creating a new folder opens up.
However, when the user clicks outside, the natural expectation would be to see this input field disappear and go back to how it was prior to clicking on `+ Folder`.

https://user-images.githubusercontent.com/20333972/136526501-7c65c898-ef91-4292-994c-cd92ca52d365.mp4

### Describe the solution you'd like

Make it so, that when the user clicks on `+ Folder` and clicks outside, the newly displayed folder name input box be disappeared, and just display the `+ Folder`.

**Comment by shub78910** [comment] 2021-10-08 10:04
Can I pick this issue?

**Comment by sherfin94** [comment] 2021-10-08 10:24
Sure, thanks, assigning you.

**Comment by saisumanthkumar** [comment] 2021-10-18 07:45
@Navaneeth-pk @sherfin94 can I work on this ??

**Comment by Navaneeth-pk** [comment] 2021-10-18 07:46
@saideepesh000 the issue is already assigned to someone.

**Comment by shub78910** [comment] 2021-10-18 07:47
@saisumanthkumar  Hey, if you have managed to set up the local environment, can you help me with that?

**Comment by Navaneeth-pk** [comment] 2021-10-18 07:50
@shub78910

**Closed as completed** 2022-01-12 02:07 UTC
Labels: good first issue, feature request, hacktoberfest
