### ISSUE TITLE
[dark mode]: fix color of time selection box in datepicker

### ISSUE THREAD

**Issue by PriteshKiri** [ToolJet/ToolJet#10087] opened 2024-06-14 13:13 UTC
### What is the current behaviour?
When using the Datepicker component in ToolJet and enabling the "Enable Time selection" option, there is a UI issue when expanding the time section. The UI is not adopting Dark mode.

### How to reproduce the issue?
1. Switch to dark mode
2. drag a datepicker
3. enable time selection from datepicker property
4. Check the color of the Time selection box

### Screenshots or Screencast
<img width="464" alt="image" src="https://github.com/ToolJet/ToolJet/assets/77957844/aa8da99c-33ec-4dba-8ac8-929a40a3098a">

**Comment by albonwu** [comment] 2024-06-14 14:58
interested in working on this - can you assign it to me?

**Comment by PriteshKiri** [comment] 2024-06-14 17:22
Assigned @albonwu. Happy coding :)

**Comment by PriteshKiri** [comment] 2024-06-20 06:44
Hey @albonwu any updates on this?

**Comment by ShyanRoyChoudhury** [comment] 2024-06-20 20:38
Hi. If there's no response can I work on this issue?

**Comment by albonwu** [comment] 2024-06-21 21:15
Hi, sorry for the late response.

It looks like the datepicker component uses react-datepicker, which uses the native HTML date picker. I've looked into it and [styling the time input field](https://stackoverflow.com/a/16106788) is the closest I've come to a cross-browser way to style the time selection box. I haven't yet found a way to change the theme of the component's popup.

**Comment by Sanil-Surve** [comment] 2024-06-24 05:37
Hey can I work on this issue because I have solution to tackle this issue so can you assign to me?

**Comment by PriteshKiri** [comment] 2024-06-24 07:50
Hey @albonwu ,

Looping @johnsoncherian in to help you with the issue.

**Comment by PriteshKiri** [comment] 2024-06-24 07:55
@ShyanRoyChoudhury @Sanil-Surve we have these two issues open for the community. Feel free to check them out.

1. https://github.com/ToolJet/ToolJet/issues/6818
2. https://github.com/ToolJet/ToolJet/issues/10132

**Comment by PriteshKiri** [comment] 2024-06-26 06:53
Hey @albonwu , are you still working on this issue?

**Comment by Sanil-Surve** [comment] 2024-06-26 13:17
Hey @PriteshKiri,  Can you assign different issue so I work on it other than above issues of the community.

**Comment by albonwu** [comment] 2024-06-26 13:37
@PriteshKiri Sorry, I've been having trouble with this one. I'm happy to let @Sanil-Surve take over if he has a solution.

**Comment by PriteshKiri** [comment] 2024-06-27 06:55
@Sanil-Surve are you still interested in working on this issue?

**Comment by harshit078** [comment] 2024-06-27 07:20
Hi @PriteshKiri , Can I take this issue up ?

**Comment by PriteshKiri** [comment] 2024-06-27 07:25
Hey @harshit078, 

Let's wait for @Sanil-Surve to respond. 

Meanwhile, you can take up any of the open issues. Sharing it here 
https://github.com/ToolJet/ToolJet/issues/9953

**Comment by Sanil-Surve** [comment] 2024-06-27 07:26
Yes I can Contribute to it.

**Comment by PriteshKiri** [comment] 2024-06-27 07:28
Assigned @Sanil-Surve. Happy coding :)

**Comment by PriteshKiri** [comment] 2024-07-02 06:20
Hey @Sanil-Surve. Any updates on the issue?

**Comment by Sanil-Surve** [comment] 2024-07-02 06:25
I'm working on issue and I think it can resolve till tonight.

**Comment by PriteshKiri** [comment] 2024-07-08 05:56
Hey @Sanil-Surve, Any updates on the issue?

**Comment by Sanil-Surve** [comment] 2024-07-08 06:02
> Hey @Sanil-Surve, Any updates on the issue?

I've found out where the issue created but I'm getting some difficulties in setting up the application

**Comment by PriteshKiri** [comment] 2024-07-09 09:36
@Sanil-Surve can you ask your queries about the setup in the contributor's channel? Here is the link to join our [Slack community](https://tooljet.slack.com/archives/C05SSQF138F/p1717070821941189)

**Comment by Sanil-Surve** [comment] 2024-07-09 16:21
Ok, I will check.

**Comment by GivenBY** [comment] 2024-07-09 18:28
Hi @PriteshKiri, I have resolved the issue. Can I take it up?

**Comment by PriteshKiri** [comment] 2024-07-10 12:42
@GivenBY will wait for @Sanil-Surve to respond with an update on the issue. You can check other issues or you can contribute to our templates as well, sharing them here.

https://github.com/ToolJet/ToolJet/issues/9923
https://github.com/ToolJet/ToolJet/issues/9924

**Comment by PriteshKiri** [comment] 2024-07-12 06:24
Hey @Sanil-Surve, any updates on this?

**Comment by Sanil-Surve** [comment] 2024-07-12 13:47
I've made changes to the codebase but not able to make PR so can you grant
permission to me.

**Comment by Sanil-Surve** [comment] 2024-07-13 14:16
> Hey @Sanil-Surve, any updates on this?
Hey @PriteshKiri !
I am not able to reproduce the issue because of that I've difficulty to contribute so you can assign it to @GivenBY

**Comment by PriteshKiri** [comment] 2024-07-13 16:50
Okay @Sanil-Surve

**Comment by GivenBY** [comment] 2024-07-14 05:23
Hey @PriteshKiri, can you assign me

**Comment by PriteshKiri** [comment] 2024-07-15 09:26
@GivenBY assiged. Happy coding.

**Comment by PriteshKiri** [comment] 2024-07-18 06:03
Thanks for your contribution @GivenBY. Moving the issue to review.

**Closed** 2024-09-30 09:42 UTC
Labels: bug, good first issue, up-for-grabs
