### ISSUE TITLE
File is saved as csv while type is selected as text on event handler

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#3692] opened 2022-07-28 08:43 UTC
### Environment
ToolJet cloud

### What is the expected behaviour?
The file should be downloaded in text/doc format.

### What is the current behaviour?
The file is being downloaded as csv.

### How to reproduce the issue?

1. Drag & drop a button.
2. Add an event handler with action type as generate a file.
3. Select type as text and enter the data and name of file.
4. Click on the file.
5. The file uses csv as an extension to be saved.

### Screenshots or Screencast
https://drive.google.com/file/d/1Vpf1v96hUrCUqEHQ7xLczsCOJVz-W7pa/view?usp=sharing

**Comment by KaviiSuri** [comment] 2022-07-31 16:01
Can I pick this up?

**Comment by withshubh** [comment] 2022-08-03 11:57
Hey @KaviiSuri 👋 
Assigned this issue to you.

**Comment by shivangT** [comment] 2022-09-06 05:54
Hey @KaviiSuri 
Please update the status for this issue. You can let us know if you need help with something.

Thanks

**Comment by KaviiSuri** [comment] 2022-09-06 08:51
Hey, I was actually stuck due to some college stuff.

I'll get to it now, but I understand if you wanna reassign this to someone.

**Comment by shivangT** [comment] 2022-09-06 09:05
Hey @KaviiSuri 

The issue is still on you. 
If you want to work on this, please go ahead. 

Incase you don't have the bandwidth to work on this, kindly let us know. We’ll re-assign this to someone else.
Thanks

**Comment by KaviiSuri** [comment] 2022-09-06 09:06
I'll get it done by tomorrow
Thanks

**Comment by shivangT** [comment] 2022-09-06 09:09
Sure, no rush @KaviiSuri 

We would appreciate if you try finishing this soon.
This issue is active for quite long. 

Thanks

**Comment by shivangT** [comment] 2022-09-19 08:23
Hey @KaviiSuri 
Any updates on the following issue?

**Comment by shubh22** [comment] 2022-09-28 05:39
Hi @KaviiSuri any update on this?

**Comment by KaviiSuri** [comment] 2022-10-06 09:27
Hey @shubh22 , I'm so sorry, but I'm facing a lot of bandwidth issues right now.

Please feel free to reassign this issue, I'll get back to contributing to ToolJet as soon as I figure things out

**Closed** 2022-10-31 08:49 UTC
Labels: bug, frontend, javascript, editor
