### ISSUE TITLE
Signup button not visible and scroll is not working

### ISSUE THREAD

**Issue by mtwn105** [ToolJet/ToolJet#1119] opened 2021-10-17 06:06 UTC
### Environment
Tooljet Prod (toolject.io)

### What is the expected behaviour?
Signup button should be visible and scrolling should be available

### What is the current behaviour?
Signup button not visible and scroll is not working

### How to reproduce the issue?

1. Enter email on homepage & Get started
2. Click on verify link in email
3. On Signup page, not able to scroll to signup button

### Screenshots or Screencast
![image](https://user-images.githubusercontent.com/12975481/137613952-d81124e0-8e80-4a45-934f-f5dd824c325a.png)

**Comment by AkshayMathurr** [comment] 2021-10-17 06:56
Hey, can I work on this issue ?

**Comment by AdhilUsman** [comment] 2021-10-17 14:42
I am not able to reproduce this issue.

**Comment by mtwn105** [comment] 2021-10-17 14:43
Hi @AdhilUsman. I did it on a 1368x766 resolution monitor. can you try zooming in?

**Comment by Navaneeth-pk** [comment] 2021-10-19 04:19
We had seen this issue before but weren't able to reproduce it at our end. Since you are able to, can you please try fixing it or help someone to reproduce the issue?
@mtwn105

**Comment by kartikth40** [comment] 2022-02-08 12:51
I recreated the issue by zooming in and out on the page and found out below problem with the page ->

https://user-images.githubusercontent.com/53307443/152988960-e4bedfef-be31-4e01-bd4c-be8175d86290.mp4

so the issue is that there are two outer containers on the page ( the two outermost blue boxes in the video), the outermost is the wider container which makes the whole view area of the page so anything inside it will be visible to the user. But the problem is the one container inside it, the vertical one containing all the content. The vertical container is scrollable so it scrolls a little bit to show all its content, but as the inner container gets out of the outer one it still scrolls to show all its content but in its own view which is out of the user's view so the solution can be making outer container scrollable as well.


**Main Issue ->**

- Outer blue container shown in the video is the user's view area

- Its inner vertical container is the scrollable area but as this container gets out of the user's view it does not show the full content as the scrollable area itself is out of the view.

**Solution ->**

- making the outer container scrollable too

**Comment by withshubh** [comment] 2022-05-19 10:45
Fixed in #2725

**Closed by withshubh** 2022-05-19 10:45 UTC
Labels: bug, good first issue, frontend, up-for-grabs
