### ISSUE TITLE
[Table component] option to select all rows (Fx)

### ISSUE THREAD

**Issue by withshubh** [ToolJet/ToolJet#8475] opened 2024-01-02 06:50 UTC
### Is your proposal related to a problem?

Currently, there is no option to select all the rows on the table programmatically after enabling the bulk selection.

### Describe the solution you'd like

Add an option to select all the rows on the table programmatically. Including the Fx.

**Comment by iamabhshk** [comment] 2024-01-04 12:48
Hii, @withshubh Can I look into this?

**Comment by nakulnagargade** [comment] 2024-02-02 07:15
This issue is duplicate of https://github.com/ToolJet/ToolJet/issues/8668. Hence closing this issue.

**Closed by nakulnagargade** 2024-02-02 07:15 UTC
Labels: feature request, roadmap, appbuilder
