### ISSUE TITLE
Changing the chart type doesn't reflect on the canvas

### ISSUE THREAD

**Issue by gondar00** [ToolJet/ToolJet#1670] opened 2021-12-29 08:49 UTC
https://user-images.githubusercontent.com/12490590/147643895-e036e7a0-3819-48f4-a1c6-5fcc2f5738ef.mov

Expected: 
Changing the chart type should reflect on the canvas

**Comment by Bhavin789** [comment] 2022-01-01 09:35
Hi @gondar00 , this seems to be a quick fix, is this worked upon or I can start working on this? Thanks!

**Comment by gondar00** [comment] 2022-01-01 09:46
@Bhavin789 no this hasn't been picked up yet, you can take it up 👍

**Comment by Bhavin789** [comment] 2022-01-02 06:21
Hi @gondar00, a PR is raised [here](https://github.com/ToolJet/ToolJet/pull/1716). You can have a look whenever you get time. I don't know how to tag reviewers and whom should I tag, so commenting the PR link here. Thanks!

And I think its a duplicate of this issue: https://github.com/ToolJet/ToolJet/issues/1578

**Closed** 2022-01-04 04:11 UTC
Labels: bug
