### ISSUE TITLE
The data of the custom component will be reset abnormally

### ISSUE THREAD

**Issue by bestpika** [ToolJet/ToolJet#4851] opened 2022-11-28 06:51 UTC
### Environment

Tooljet | docker | v1.29.0

### What is the expected behaviour?

The properties of `data` should be kept up to date.

### What is the current behaviour?

Except for the modified properties, the initial value will be changed back.

### How to reproduce the issue?

If my `data` has more than one property, whenever I set one of the properties, the other two properties will automatically change back to their initial values.

1. Press button3
1. Press button2
1. Press button1

My data:

```
{{{ 
  button1: true,
  button2: true,
  button3: ''
}}}
```

My code:

```jsx
import React from 'https://cdn.skypack.dev/react'
import ReactDOM from 'https://cdn.skypack.dev/react-dom'
import { Button, Container } from 'https://cdn.skypack.dev/@material-ui/core'
const MyCustomComponent = ({ data, updateData, runQuery }) => (
  <div>
    <Button variant="contained" onClick={() => { updateData({ button1: false }); console.warn(data) }}>{`${data.button1}`}</Button>
    <Button variant="contained" onClick={() => { updateData({ button2: false }); console.warn(data) }}>{`${data.button2}`}</Button>
    <Button variant="contained" onClick={() => { updateData({ button3: 'TEXT' }); console.warn(data) }}>{`${data.button3}`}</Button>
  </div>
)
const ConnectedComponent = Tooljet.connectComponent(MyCustomComponent)
ReactDOM.render(<ConnectedComponent />, document.body)
```

### Screenshots or Screencast

Initial
![image](https://user-images.githubusercontent.com/5698157/204209590-70a1b131-3de7-4389-9052-a5a96bd3fbb1.png)
Press button3
![image](https://user-images.githubusercontent.com/5698157/204209634-f6ab0a19-974b-43a4-901e-1944119534a5.png)
Press button2
![image](https://user-images.githubusercontent.com/5698157/204209714-79c4da1b-4bca-4ec9-8d9d-d19cca793b48.png)
Press button 2
![image](https://user-images.githubusercontent.com/5698157/204209754-326053a2-7468-4859-afa3-3a3b5e174a81.png)

### Please provide any traces or logs that could help here.

```json
{"button1": true, "button2": true, "button3": "TEXT"}
{"button1": true, "button2": false, "button3": ""}
{"button1": false, "button2": true, "button3": ""}
```

### Any possible solutions?

N/A

### Can you identify the location in the driver source code where the problem exists?

https://github.com/ToolJet/ToolJet/blob/65baf7232b28ec62d333aaaaa58eb2f17494cb67/frontend/src/Editor/Components/CustomComponent/iframe.html#L37-L59

**Comment by kavinvenkatachalam** [comment] 2022-11-30 02:55
Hi @bestpika,

Spreading the data while updating would fix this issue. Attaching the working code below,

```jsx
import React from 'https://cdn.skypack.dev/react'
import ReactDOM from 'https://cdn.skypack.dev/react-dom'
import { Button, Container } from 'https://cdn.skypack.dev/@material-ui/core'
const MyCustomComponent = ({ data, updateData, runQuery }) => (
  <div>
    <Button variant="contained" onClick={() => { updateData({ ...data, button1: false }); console.warn(data) }}>{`${data.button1}`}</Button>
    <Button variant="contained" onClick={() => { updateData({ ...data, button2: false }); console.warn(data) }}>{`${data.button2}`}</Button>
    <Button variant="contained" onClick={() => { updateData({ ...data, button3: 'TEXT' }); console.warn(data) }}>{`${data.button3}`}</Button>
  </div>
)
const ConnectedComponent = Tooljet.connectComponent(MyCustomComponent)
ReactDOM.render(<ConnectedComponent />, document.body)
```

Attaching the GIF,

![custom](https://user-images.githubusercontent.com/50441969/204696249-78ae8261-3f76-4540-95cd-74c2e6b0a96f.gif)

Closing the issue as this is not a bug.

**Closed by kavinvenkatachalam** 2022-11-30 02:55 UTC
Labels: bug, frontend, widget

**Comment by bestpika** [comment] 2022-12-01 03:10
@kavinvenkatachalam 
I thought you were using something like React's `setState` to do this, but it doesn't look like it.
Shouldn't you change the documentation examples along with it?
https://docs.tooljet.com/docs/widgets/custom-component/#code
Thank you.

**Comment by kavinvenkatachalam** [comment] 2022-12-01 03:13
Thanks for the feedback @bestpika. We'll try update the docs soon.
cc: @withshubh
