### ISSUE TITLE
The wrong environment data source option is getting updated when running Rest API Oauth 2.0.

### ISSUE THREAD

**Issue by shah21** [ToolJet/ToolJet#6294] opened 2023-05-08 17:25 UTC
### Version Information
Tooljet Cloud
### What is the expected behaviour?

Should update the correct environment. example, if the user is running the app in the production environment, it should only update the production data source options.

### What is the current behaviour?

Wrong environment data source options get updated when running RestAPI Oauth 2.0
### How to reproduce the issue?
Note: This issue is hard to reproduce. though, you can try these steps

1. Add a new global RestAPI data source with Oauth 2.0 authentication
2. Create a new app & Rest API queries
3. Run & observe

### Screenshots or Screencast

<img width="701" alt="Screenshot 2023-05-08 at 10 53 05 PM" src="https://user-images.githubusercontent.com/18279004/236889685-979555c1-c26f-40f5-91dd-4f4960c0f392.png">

### Can you identify the location in the driver source code where the problem exists?
data source controller -> authorize_oauth2 API

**Comment by thehacklady** [comment] 2023-10-26 09:33
Unable to reproduce. Closing the issue.

**Closed by thehacklady** 2023-10-26 09:33 UTC
Labels: bug, roadmap, platform
