### ISSUE TITLE
Form Submit Button Resets in New Application Versions

### ISSUE THREAD

**Issue by AllenAJ** [ToolJet/ToolJet#8959] opened 2024-03-01 09:54 UTC
### What is the expected behaviour?

  Whenever I create a new version, the form submit button should not reset.

### What is the current behaviour?

  Each time I create a new version, the form submit button gets reset.

### How to reproduce the issue?
1. In the app builder, drag the form component
2. In properties, choose 'Button to submit' option.
3. Now, create a new version(v1 to v2)
4. Go to the form properties again and you'll see that 'Button to submit' option is reset. 

### Screenshots or Screencast
![form v1]( https://img001.prntscr.com/file/img001/mTx10q61StqhtferR-S_gQ.png)
![form v2]( https://img001.prntscr.com/file/img001/3cVbp8LOT4K4Cz69eCNH-w.png)

### If the bug is confirmed, would you be willing to submit a PR?
No

**Comment by maheshkeswani** [comment] 2024-03-19 16:52
Hey @karan-rathod-316  I m willing to work on this issue .

**Comment by 2001asjad** [comment] 2024-03-20 05:38
Sure @maheshkeswani , go ahead.

**Comment by PrashantIndurkar** [comment] 2024-04-07 12:02
@maheshkeswani Hello are you still working on this issue?

**Comment by JunedKhan101** [comment] 2024-04-07 12:29
Hi @2001asjad I'd like to work on this. Kindly assign this to me.

**Comment by 2001asjad** [comment] 2024-04-07 18:34
Hey @maheshkeswani , let us know if you're still working on this issue.

**Comment by maheshkeswani** [comment] 2024-04-07 21:02
Hey @2001asjad ,I have unassigned myself U Can assing it to someone else

**Comment by 2001asjad** [comment] 2024-04-08 09:07
Hey, @PrashantIndurkar, I am assigning this issue to you. Do let us know if you're moving forward with it.

**Comment by 2001asjad** [comment] 2024-04-15 07:00
Hello @PrashantIndurkar , are you still working on this issue?

**Comment by 2001asjad** [comment] 2024-04-16 05:22
Since there has been no confirmation from the previous assignee, @JunedKhan101 I am assigning this issue to you.

**Comment by Sadaf-A** [comment] 2024-04-19 17:27
Hey @AllenAJ , 
I'd like to have a go at this if you could please assign it to me.

**Comment by 2001asjad** [comment] 2024-04-19 18:34
@JunedKhan101 , let us know if you're going forward with the issue.

**Comment by JunedKhan101** [comment] 2024-04-19 18:38
I'm facing some issues to setup the project, you can assign this to someone else.

**Comment by 2001asjad** [comment] 2024-04-19 18:44
@Sadaf-A, I am assigning this issue to you. Thanks for contributing to ToolJet.

**Comment by Sadaf-A** [comment] 2024-04-20 08:50
@2001asjad 
The issue is arising because we assign the submission button through it's ID and we generate a new ID for each new component and the previous ID which was assigned to the submission button becomes obsolete
I have solved this issue by assigning the old component's id to the new component while generating new components in the `createNewPagesAndComponentsForVersion()` function
I have tested this does it seem to be a viable solution? since, the ids will still be unique I don't think it should be a problem

**Comment by karan-rathod-316** [comment] 2024-04-20 11:54
Thank you for your inputs @Sadaf-A, I will ask someone to review this on Monday:-).

**Comment by karan-rathod-316** [comment] 2024-05-17 11:00
Closing this issue since it was covered in a different PR.

**Closed by karan-rathod-316** 2024-05-17 11:00 UTC
Labels: bug, roadmap, appbuilder
