### ISSUE TITLE
Dashboard search animation to be be fixed to top of the page

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#8891] opened 2024-02-22 06:29 UTC
**Pain point**- Search animation disrupts the UI completely, and moves vertically 

**Solution**- The search bar should be anchored to the top of the page, only the cards should change from all apps -> loading state -> search results 

Screen recording for ref- 

https://github.com/ToolJet/ToolJet/assets/127945292/04a05035-b374-460b-a9c2-d5f5d8bf2554

**Comment by tiwarishankar** [comment] 2024-03-01 17:48
Hey @nechalmaggon,

I understand the issue ( #8891) regarding the UI disruption caused by the search animation and the solution involving anchoring the search bar to the top of the page. I'm eager to contribute to resolving this and would like to know if I may start working on it .

**Comment by karan-rathod-316** [comment] 2024-03-04 14:27
Hi @tiwarishankar, I am assigning this issue to you. Thank you so much for your interest in contributing to ToolJet.

**Comment by tiwarishankar** [comment] 2024-03-04 19:04
Hi @karan-rathod-316 ,

Thank you for assigning me this issue.

I wanted to provide a quick update: currently, I am working with Version 2.32.0 locally, and for this particular version, the search functionality appears as follows:

Screen-recording in my local:

https://github.com/ToolJet/ToolJet/assets/71537738/22a1cdf0-7eae-4809-ae2f-fceac82d4fa9


Current Problem: While searching, there is no loading state, and because of that, the search UI does not get disrupted.

I also checked the production version (2.30.3-ee2.15.7-cloud2.3.5), and there the problem described in issue #8891 exists. Here is a screen recording of the issue in production:

Screen-recording of production:

https://github.com/ToolJet/ToolJet/assets/71537738/6af6db1f-3ce0-4c10-96b2-e8d2dfa0cdf6

**Closed** 2024-07-24 14:47 UTC
Labels: bug, roadmap, platform
