### ISSUE TITLE
[localization] Translate App Card in Japanese

### ISSUE THREAD

**Issue by vedant-z** [ToolJet/ToolJet#4281] opened 2022-10-04 07:10 UTC
### Is your proposal related to a problem?

Add translations for App Card strings in Japanese.

### Describe the solution you'd like

The strings need to be translated:
```
"appCard":{
            "changeIcon":"Change Icon",
            "addToFolder":"Add to folder",
            "move":"Move",
            "to":"to",
            "selectFolder":"Select folder",
            "deleteApp":"Delete app",
            "exportApp":"Export app",
            "cloneApp":"Clone app",
            "launch":"Launch",
            "maintenance":"Maintenance",
            "noDeployedVersion":"App does not have a deployed version",
            "openInAppViewer":"Open in app viewer",
            "removeFromFolder":"Remove from folder"
        },
```

### Describe alternatives you've considered

Here's the guide to contributing to [localization](https://docs.tooljet.com/docs/contributing-guide/l10n)

### If the feature is approved, would you be willing to submit a PR?

YES
Assign to me and I'll work on it!

**Comment by sidbelbase** [comment] 2022-10-04 13:59
hi can you assign this task to me?

**Comment by vedant-z** [comment] 2022-10-04 14:12
Sorry @sidbelbase 

Actually I want to work on it, if it's confirmed.

**Comment by withshubh** [comment] 2022-10-13 11:26
Hey @vedant-z  👋 

Thanks for your interest in contributing to ToolJet. 

Closing the issue as we are only accepting localization contributions for the issues that we create unless the issue is created by the native speaker. You can always check out other open issues. 😇

**Closed** 2022-10-13 11:26 UTC
Labels: feature request
